// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class ApplicationWarmupProcessLog
{
    public int Id { get; set; }

    public int ProcessId { get; set; }

    public DateTime ExecutionDate { get; set; }

    public string? Message { get; set; }

    public virtual ApplicationWarmupProcess Process { get; set; } = null!;
}
