// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Data.ResultTypes
{
    public partial class cmdStruct_sp_GetAllSubUnitsForUnitResult
    {
        public int? CS_ID { get; set; }
        [StringLength(100)]
        public string? LONG_NAME { get; set; }
        [StringLength(4)]
        public string? PAS_CODE { get; set; }
        public int? Parent_CS_ID { get; set; }
        public int? LevelDown { get; set; }
    }
}

