// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class ConversionRun
{
    public int RunId { get; set; }

    public DateTime StartDatestamp { get; set; }

    public DateTime? EndDatestamp { get; set; }

    public string? Status { get; set; }

    public int? RecordsProcessed { get; set; }

    public int? ErrosFound { get; set; }

    public string? LastUserId { get; set; }

    public string? LastPatientId { get; set; }

    public string? LastLodCaseId { get; set; }
}
