// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class ConversionRunLog
{
    public int RunId { get; set; }

    public int LineNumber { get; set; }

    public string Message { get; set; } = null!;
}
