// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreMessage
{
    public short MessageId { get; set; }

    public string Message { get; set; } = null!;

    public string? Title { get; set; }

    public string Name { get; set; } = null!;

    public int CreatedBy { get; set; }

    public bool Popup { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public bool IsAdminMessage { get; set; }
}
