// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreWorkflowCertificationStampMap
{
    public byte WorkflowId { get; set; }

    public int CertStampId { get; set; }

    public virtual CoreCertificationStamp CertStamp { get; set; } = null!;

    public virtual CoreWorkflow Workflow { get; set; } = null!;
}
