// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreLkupPeppcaseType
{
    public int CaseTypeId { get; set; }

    public string CaseTypeName { get; set; } = null!;

    public bool Active { get; set; }
}
