// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreWorkflowFinding
{
    public byte WorkflowId { get; set; }

    public byte FindingId { get; set; }

    public int? SortOrder { get; set; }

    public virtual CoreLkUpFinding Finding { get; set; } = null!;

    public virtual CoreWorkflow Workflow { get; set; } = null!;
}
