// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreWorkflowPermission
{
    public byte? WorkflowId { get; set; }

    public short? PermId { get; set; }

    public virtual CorePermission? Perm { get; set; }

    public virtual CoreWorkflow? Workflow { get; set; }
}
