// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreLkupOccurrenceDescription
{
    public int OccurrenceId { get; set; }

    public string OccurrenceDescription { get; set; } = null!;

    public int SortOrder { get; set; }
}
