// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreStatusCodeSigner
{
    public int Status { get; set; }

    public byte GroupId { get; set; }

    public virtual CoreUserGroup Group { get; set; } = null!;

    public virtual CoreWorkStatus StatusNavigation { get; set; } = null!;
}
