// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreLkupTimeZone
{
    public string ZoneId { get; set; } = null!;

    public string Description { get; set; } = null!;

    public bool Active { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; } = null!;

    public DateTime ModifiedDate { get; set; }

    public string ModifiedBy { get; set; } = null!;

    public virtual ICollection<CommandStruct> CommandStructs { get; set; } = new List<CommandStruct>();

    public virtual ICollection<TestCommandStruct> TestCommandStructs { get; set; } = new List<TestCommandStruct>();
}
