// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreKeyValKey
{
    public int Id { get; set; }

    public string? Description { get; set; }

    public int KeyTypeId { get; set; }

    public virtual ICollection<CoreKeyValValue> CoreKeyValValues { get; set; } = new List<CoreKeyValValue>();

    public virtual CoreKeyValKeyType KeyType { get; set; } = null!;
}
