// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreKeyValValue
{
    public int Id { get; set; }

    public int KeyId { get; set; }

    public string? ValueId { get; set; }

    public string? Value { get; set; }

    public string ValueDescription { get; set; } = null!;

    public virtual CoreKeyValKey Key { get; set; } = null!;
}
