// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreLkupGrade
{
    public int Code { get; set; }

    public string? Rank { get; set; }

    public string? Grade { get; set; }

    public string? Title { get; set; }

    public short? Displayorder { get; set; }

    public virtual ICollection<CoreUser> CoreUsers { get; set; } = new List<CoreUser>();

    public virtual ICollection<CoreWorkStatusTracking> CoreWorkStatusTrackings { get; set; } = new List<CoreWorkStatusTracking>();

    public virtual ICollection<Form348ApSarc> Form348ApSarcs { get; set; } = new List<Form348ApSarc>();

    public virtual ICollection<Form348Ap> Form348Aps { get; set; } = new List<Form348Ap>();

    public virtual ICollection<Form348Rr> Form348Rrs { get; set; } = new List<Form348Rr>();

    public virtual ICollection<Form348Sarc> Form348Sarcs { get; set; } = new List<Form348Sarc>();

    public virtual ICollection<Form348> Form348s { get; set; } = new List<Form348>();

    public virtual ICollection<GradeAbbreviation> GradeAbbreviations { get; set; } = new List<GradeAbbreviation>();

    public virtual ICollection<MemberDatum> MemberData { get; set; } = new List<MemberDatum>();
}
