// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Data.ResultTypes
{
    public partial class core_lookups_sp_GetDataTypesResult
    {
        public int Id { get; set; }
        [StringLength(100)]
        public string Name { get; set; } = default!;
    }
}

