// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreMessagesRead
{
    public short MessageId { get; set; }

    public int UserId { get; set; }

    public DateTime DateRead { get; set; }
}
