// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreLkupPersonnelType
{
    public short Id { get; set; }

    public string Description { get; set; } = null!;

    public bool Formal { get; set; }

    public string? RoleName { get; set; }

    public virtual ICollection<Form348ApFinding> Form348ApFindings { get; set; } = new List<Form348ApFinding>();

    public virtual ICollection<Form348ApSarcFinding> Form348ApSarcFindings { get; set; } = new List<Form348ApSarcFinding>();

    public virtual ICollection<Form348Finding> Form348Findings { get; set; } = new List<Form348Finding>();

    public virtual ICollection<Form348RrFinding> Form348RrFindings { get; set; } = new List<Form348RrFinding>();

    public virtual ICollection<Form348SarcFinding> Form348SarcFindings { get; set; } = new List<Form348SarcFinding>();

    public virtual ICollection<Form348> Form348s { get; set; } = new List<Form348>();
}
