// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CorePkgImportError
{
    public int Id { get; set; }

    public string? StoredProcName { get; set; }

    public string? KeyValue { get; set; }

    public int? PkgLogId { get; set; }

    public DateTime? Time { get; set; }

    public string? ErrorMessage { get; set; }
}
