// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreUserRole
{
    /// <summary>
    /// userRoleID identifies UserRoles
    /// </summary>
    public int UserRoleId { get; set; }

    /// <summary>
    /// roleID from table Roles
    /// </summary>
    public byte GroupId { get; set; }

    /// <summary>
    /// UserId from table Users
    /// </summary>
    public int UserId { get; set; }

    public byte Status { get; set; }

    public bool Active { get; set; }

    public virtual ICollection<CoreUser> CoreUsers { get; set; } = new List<CoreUser>();

    public virtual CoreUserGroup Group { get; set; } = null!;

    public virtual CoreLkupAccessStatus StatusNavigation { get; set; } = null!;

    public virtual CoreUser User { get; set; } = null!;
}
