// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Data.ResultTypes
{
    public partial class core_workstatus_sp_GetWorkStatusDescriptionResult
    {
        [StringLength(50)]
        public string Description { get; set; } = default!;
    }
}

