// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Data.ResultTypes
{
    public partial class core_user_sp_GetUsersAltTitleByGroupResult
    {
        public int userID { get; set; }
        [StringLength(100)]
        public string username { get; set; } = default!;
        [StringLength(201)]
        public string Name { get; set; } = default!;
        [StringLength(100)]
        public string? Title { get; set; }
    }
}

