// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreEmailTemplate
{
    public int TemplateId { get; set; }

    public string? Compo { get; set; }

    public string Title { get; set; } = null!;

    public string Subject { get; set; } = null!;

    public string Body { get; set; } = null!;

    public string? DataProc { get; set; }

    public bool Active { get; set; }

    public DateTime SysDate { get; set; }

    public virtual ICollection<ReminderEmailSetting> ReminderEmailSettings { get; set; } = new List<ReminderEmailSetting>();
}
