// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreLkupAction
{
    public byte ActionId { get; set; }

    public string ActionName { get; set; } = null!;

    public bool Hide { get; set; }

    public bool? LogChanges { get; set; }

    public virtual ICollection<CoreLogAction> CoreLogActions { get; set; } = new List<CoreLogAction>();
}
