// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreLogErrorArchive
{
    public int LogId { get; set; }

    public DateTime ErrorTime { get; set; }

    public string? UserName { get; set; }

    public string? Page { get; set; }

    public string? AppVersion { get; set; }

    public string? Browser { get; set; }

    public string? Message { get; set; }

    public string? StackTrace { get; set; }

    public string? Caller { get; set; }

    public string? Address { get; set; }
}
