// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreLogAction
{
    public int LogId { get; set; }

    public byte ModuleId { get; set; }

    public byte ActionId { get; set; }

    public DateTime ActionDate { get; set; }

    public int UserId { get; set; }

    /// <summary>
    /// referenceId might be LODId, IncapId, AppealId, Budget, etc.  Not null and not FK
    /// </summary>
    public int? ReferenceId { get; set; }

    public string? Notes { get; set; }

    public int? Status { get; set; }

    public int? NewStatus { get; set; }

    public string? Address { get; set; }

    public virtual CoreLkupAction Action { get; set; } = null!;

    public virtual CoreLkupModule Module { get; set; } = null!;

    public virtual CoreUser User { get; set; } = null!;
}
