// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreLkupDutyStatus
{
    public byte DutyId { get; set; }

    public string? DutyType { get; set; }

    public string DutyDescription { get; set; } = null!;

    public int? SortOrder { get; set; }
}
