// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreLkupRuleType
{
    public byte Id { get; set; }

    public string Description { get; set; } = null!;

    public virtual ICollection<CoreLkupRule> CoreLkupRules { get; set; } = new List<CoreLkupRule>();
}
