// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreWorkflowInitStatus
{
    public byte WorkflowId { get; set; }

    public byte GroupId { get; set; }

    public int StatusId { get; set; }

    public virtual CoreUserGroup Group { get; set; } = null!;

    public virtual CoreWorkStatus Status { get; set; } = null!;

    public virtual CoreWorkflow Workflow { get; set; } = null!;
}
