// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Data.ResultTypes
{
    public partial class core_sp_GetIRILOAssociableSpecialCasesResult
    {
        public int RefId { get; set; }
        [StringLength(50)]
        public string CaseId { get; set; } = default!;
        [StringLength(50)]
        public string moduleName { get; set; } = default!;
    }
}

