// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Data.ResultTypes
{
    public partial class core_lookUps_sp_GetPEPPCaseTypesResult
    {
        public int Value { get; set; }
        [StringLength(50)]
        public string Name { get; set; } = default!;
        public bool active { get; set; }
    }
}

