// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreWorkStatusTracking
{
    public int WstId { get; set; }

    public int WsId { get; set; }

    public int RefId { get; set; }

    public byte Module { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int? CompletedBy { get; set; }

    public byte? WorkflowId { get; set; }

    public int? Rank { get; set; }

    public string? Name { get; set; }

    public virtual CoreUser? CompletedByNavigation { get; set; }

    public virtual CoreLkupModule ModuleNavigation { get; set; } = null!;

    public virtual CoreLkupGrade? RankNavigation { get; set; }

    public virtual CoreWorkflow? Workflow { get; set; }

    public virtual CoreWorkStatus Ws { get; set; } = null!;
}
