// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreWorkStatusRule
{
    public int WsrId { get; set; }

    public int WsoId { get; set; }

    public byte RuleId { get; set; }

    public string RuleData { get; set; } = null!;

    public bool? CheckAll { get; set; }

    public virtual CoreLkupRule Rule { get; set; } = null!;

    public virtual CoreWorkStatusOption Wso { get; set; } = null!;
}
