// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Data.ResultTypes
{
    public partial class core_lookups_sp_GetAllRMUsResult
    {
        public int Id { get; set; }
        [StringLength(255)]
        public string? RMU { get; set; }
        public int? cs_id { get; set; }
    }
}

