// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreStatusCode
{
    public int StatusId { get; set; }

    public string Description { get; set; } = null!;

    public byte ModuleId { get; set; }

    public string Compo { get; set; } = null!;

    public byte? GroupId { get; set; }

    public bool IsFinal { get; set; }

    public bool IsApproved { get; set; }

    public bool CanAppeal { get; set; }

    public string? Filter { get; set; }

    public byte DisplayOrder { get; set; }

    public bool? IsCancel { get; set; }

    public bool IsDisposition { get; set; }

    public bool IsFormal { get; set; }

    public virtual ICollection<CoreWorkStatus> CoreWorkStatuses { get; set; } = new List<CoreWorkStatus>();

    public virtual CoreUserGroup? Group { get; set; }

    public virtual CoreLkupModule Module { get; set; } = null!;
}
