// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreMemoGroup
{
    public int Id { get; set; }

    public byte TemplateId { get; set; }

    public byte GroupId { get; set; }

    public bool CanCreate { get; set; }

    public bool CanEdit { get; set; }

    public bool CanDelete { get; set; }

    public bool CanView { get; set; }

    public virtual CoreUserGroup Group { get; set; } = null!;

    public virtual CoreMemoTemplate Template { get; set; } = null!;
}
