// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Data.ResultTypes
{
    public partial class core_group_sp_GetAllWithManagedResult
    {
        public byte GroupId { get; set; }
        [StringLength(100)]
        public string Name { get; set; } = default!;
        public bool? Manages { get; set; }
        public bool Notify { get; set; }
        public bool? ViewBy { get; set; }
    }
}

