// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreLkupIcd7thChar
{
    public string? CharCode { get; set; }

    public string? CharExt { get; set; }

    public string? CharDef { get; set; }
}
