// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CoreLkupPwcategory
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? ParaInfo { get; set; }
}
