// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class CorePermission
{
    public short PermId { get; set; }

    public string PermName { get; set; } = null!;

    public string PermDesc { get; set; } = null!;

    public bool Exclude { get; set; }
}
