// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Data.ResultTypes
{
    public partial class dev_sp_GetDevLoginsResult
    {
        public int? userId { get; set; }
        [StringLength(50)]
        public string? edipin { get; set; }
        [StringLength(102)]
        public string? name { get; set; }
    }
}

