// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class DevUnit
{
    public int CsId { get; set; }

    public string UnitType { get; set; } = null!;

    public int? OrderNum { get; set; }
}
