// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Data.ResultTypes
{
    public partial class docs_GetRedactedCatsByViewResult
    {
        public int DocCatId { get; set; }
        [StringLength(150)]
        public string CategoryDescription { get; set; } = default!;
    }
}

