// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class Form348ApSarc
{
    public int AppealSarcId { get; set; }

    public int InitialId { get; set; }

    public int InitialWorkflow { get; set; }

    public string CaseId { get; set; } = null!;

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int Status { get; set; }

    public byte? Workflow { get; set; }

    public int? CancelReason { get; set; }

    public string? CancelExplanation { get; set; }

    public DateTime? CancelDate { get; set; }

    public byte? RwoaReason { get; set; }

    public string? RwoaExplanation { get; set; }

    public DateTime? RwoaDate { get; set; }

    public string? RwoaReply { get; set; }

    public int? ReturnToGroup { get; set; }

    public int? ReturnByGroup { get; set; }

    public string MemberName { get; set; } = null!;

    public string MemberSsn { get; set; } = null!;

    public DateTime? SigDateWingSarc { get; set; }

    public string? SigNameWingSarc { get; set; }

    public string? SigTitleWingSarc { get; set; }

    public DateTime? SigDateSarcAdmin { get; set; }

    public string? SigNameSarcAdmin { get; set; }

    public string? SigTitleSarcAdmin { get; set; }

    public DateTime? SigDateAppellateAuth { get; set; }

    public string? SigNameAppellateAuth { get; set; }

    public string? SigTitleAppellateAuth { get; set; }

    public DateTime? SigDateBoardMedical { get; set; }

    public string? SigNameBoardMedical { get; set; }

    public string? SigTitleBoardMedical { get; set; }

    public DateTime? SigDateBoardLegal { get; set; }

    public string? SigNameBoardLegal { get; set; }

    public string? SigTitleBoardLegal { get; set; }

    public DateTime? SigDateBoardAdmin { get; set; }

    public string? SigNameBoardAdmin { get; set; }

    public string? SigTitleBoardAdmin { get; set; }

    public string? ReturnComment { get; set; }

    public int? DocGroupId { get; set; }

    public bool? MemberNotified { get; set; }

    public byte? ConsultationFromUsergroupId { get; set; }

    public bool IsPostProcessingComplete { get; set; }

    public string MemberUnit { get; set; } = null!;

    public int MemberUnitId { get; set; }

    public string MemberCompo { get; set; } = null!;

    public int MemberGrade { get; set; }

    public bool IsNonDbsignCase { get; set; }

    public virtual ICollection<Form348ApSarcFinding> Form348ApSarcFindings { get; set; } = new List<Form348ApSarcFinding>();

    public virtual Form348PostProcessingAppealSarc? Form348PostProcessingAppealSarc { get; set; }

    public virtual CoreLkupGrade MemberGradeNavigation { get; set; } = null!;
}
