// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class Form348Ap
{
    public int AppealId { get; set; }

    public int InitialLodId { get; set; }

    public string CaseId { get; set; } = null!;

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? Workflow { get; set; }

    public int? Status { get; set; }

    public int? CancelReason { get; set; }

    public string? CancelExplanation { get; set; }

    public DateTime? CancelDate { get; set; }

    public byte? RwoaReason { get; set; }

    public DateTime? RwoaDate { get; set; }

    public string? RwoaExplanation { get; set; }

    public int? ReturnToGroup { get; set; }

    public int? ReturnByGroup { get; set; }

    public DateTime? SigDatePm { get; set; }

    public string? SigNamePm { get; set; }

    public string? SigTitlePm { get; set; }

    public DateTime? SigDateBoardTech { get; set; }

    public string? SigNameBoardTech { get; set; }

    public string? SigTitleBoardTech { get; set; }

    public DateTime? SigDateBoardMedical { get; set; }

    public string? SigNameBoardMedical { get; set; }

    public string? SigTitleBoardMedical { get; set; }

    public DateTime? SigDateBoardLegal { get; set; }

    public string? SigNameBoardLegal { get; set; }

    public string? SigTitleBoardLegal { get; set; }

    public DateTime? SigDateBoardAdmin { get; set; }

    public string? SigNameBoardAdmin { get; set; }

    public string? SigTitleBoardAdmin { get; set; }

    public DateTime? SigDateApprovingAuth { get; set; }

    public string? SigNameApprovingAuth { get; set; }

    public string? SigTitleApprovingAuth { get; set; }

    public DateTime? SigDateAppellateAuth { get; set; }

    public string? SigNameAppellateAuth { get; set; }

    public string? SigTitleAppellateAuth { get; set; }

    public byte? LodPmApproved { get; set; }

    public byte? BoardTechApproved { get; set; }

    public byte? BoardMedicalApproved { get; set; }

    public byte? BoardLegalApproved { get; set; }

    public byte? BoardAdminApproved { get; set; }

    public byte? ApprovalAuthApproved { get; set; }

    public byte? AppellateAuthApproved { get; set; }

    public string? LodPmApprovalComment { get; set; }

    public string? BoardTechApprovalComment { get; set; }

    public string? BoardMedicalApprovalComment { get; set; }

    public string? BoardLegalApprovalComment { get; set; }

    public string? BoardAdminApprovalComment { get; set; }

    public string? ApprovalAuthApprovalComment { get; set; }

    public string? AppellateAuthApprovalComment { get; set; }

    public string? ReturnComment { get; set; }

    public string? MemberSsn { get; set; }

    public string? MemberName { get; set; }

    public int? DocGroupId { get; set; }

    public bool? MemberNotified { get; set; }

    public bool IsPostProcessingComplete { get; set; }

    public string MemberUnit { get; set; } = null!;

    public int MemberUnitId { get; set; }

    public string MemberCompo { get; set; } = null!;

    public int MemberGrade { get; set; }

    public bool IsNonDbsignCase { get; set; }

    public virtual ICollection<Form348ApFinding> Form348ApFindings { get; set; } = new List<Form348ApFinding>();

    public virtual CoreLkupGrade MemberGradeNavigation { get; set; } = null!;
}
