// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class Form348ApSarcFinding
{
    public int Id { get; set; }

    public int AppealId { get; set; }

    public short? Ptype { get; set; }

    public string? Ssn { get; set; }

    public string? Name { get; set; }

    public string? Grade { get; set; }

    public string? Compo { get; set; }

    public int? Finding { get; set; }

    public string? Remarks { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string? Pascode { get; set; }

    public string? Rank { get; set; }

    public string? FindingsText { get; set; }

    public bool IsLegacyFinding { get; set; }

    public string? Concur { get; set; }

    public virtual Form348ApSarc Appeal { get; set; } = null!;

    public virtual CoreUser? CreatedByNavigation { get; set; }

    public virtual CoreUser? ModifiedByNavigation { get; set; }

    public virtual CoreLkupPersonnelType? PtypeNavigation { get; set; }
}
