// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class Form348IncapFinding
{
    public int ScId { get; set; }

    public DateTime? InitStartDate { get; set; }

    public DateTime? InitEndDate { get; set; }

    public bool? InitExtOrComplete { get; set; }

    public bool? InitAppealOrComplete { get; set; }

    public string? MedReportType { get; set; }

    public bool? MedAbilityToPreform { get; set; }

    public bool? ICRecommendation { get; set; }

    public bool? WingJaConcur { get; set; }

    public bool? FinIncomeLost { get; set; }

    public bool? WccInitApproval { get; set; }

    public bool? InitLateSubmission { get; set; }

    public bool? FinSelfEmployed { get; set; }

    public virtual ICollection<Form348IncapAppeal> Form348IncapAppeals { get; set; } = new List<Form348IncapAppeal>();

    public virtual ICollection<Form348IncapExt> Form348IncapExts { get; set; } = new List<Form348IncapExt>();
}
