// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class Form348Finding
{
    public int Id { get; set; }

    public int Lodid { get; set; }

    public short Ptype { get; set; }

    public string? Ssn { get; set; }

    public string? Name { get; set; }

    public string? Grade { get; set; }

    public string? Compo { get; set; }

    public string? Rank { get; set; }

    public string? Pascode { get; set; }

    public byte? Finding { get; set; }

    public string? DecisionYn { get; set; }

    public string? Explanation { get; set; }

    public int ModifiedBy { get; set; }

    public DateTime ModifiedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string? FindingsText { get; set; }

    public bool? ReferDes { get; set; }

    public bool? Lodinitiation { get; set; }

    public bool? WrittenDiagnosis { get; set; }

    public bool? MemberRequest { get; set; }

    public string? CorrectlyIdentified { get; set; }

    public string? VerifiedAndAttached { get; set; }

    public string? Idtstatus { get; set; }

    public bool? Ipcarsattached { get; set; }

    public bool? EightYearRule { get; set; }

    public bool? PriorToDutytatus { get; set; }

    public string? StatusWorsened { get; set; }

    public virtual CoreUser CreatedByNavigation { get; set; } = null!;

    public virtual Form348 Lod { get; set; } = null!;

    public virtual CoreUser ModifiedByNavigation { get; set; } = null!;

    public virtual CoreLkupPersonnelType PtypeNavigation { get; set; } = null!;
}
