// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class ImpHistory
{
    public int? AlodUserid { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int? WsId { get; set; }

    public string? Username { get; set; }

    public int? AlodLodid { get; set; }
}
