// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class ImpLodmapping
{
    public int? AlodLodId { get; set; }

    public int RcphaLodid { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? RcPhaOrgLodid { get; set; }

    public string? CaseId { get; set; }

    public int? AlodStatus { get; set; }

    public int? RcphaValidStatus { get; set; }

    public string? RcphaValidStatusMeaning { get; set; }

    public string? RcphaProcName { get; set; }
}
