// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class ImpLodAaMapping
{
    public string? ImportName { get; set; }

    public string? Name { get; set; }

    public string? Rank { get; set; }

    public string? Branch { get; set; }
}
