// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class ImpLodRwoa
{
    public string? RwoaId { get; set; }

    public string? LodId { get; set; }

    public string? SentTo { get; set; }

    public string? ReasonSentBack { get; set; }

    public string? ExplanationForSendingBack { get; set; }

    public string? Sender { get; set; }

    public string? DateSent { get; set; }

    public string? CommentsBackToSender { get; set; }

    public string? DateSentBack { get; set; }

    public string? CreatedBy { get; set; }

    public string? CreatedDate { get; set; }
}
