// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class ImpUsermapping
{
    public int? UserId { get; set; }

    public int? PersonId { get; set; }

    public string? Username { get; set; }
}
