// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class ImpUserrole
{
    public string? Username { get; set; }

    public string? Permission { get; set; }

    public int? Groupid { get; set; }

    public bool? IsDefault { get; set; }
}
