// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Data.ResultTypes
{
    public partial class PH_FormValue_sp_GetByRefIdResult
    {
        public int RefId { get; set; }
        public int SectionId { get; set; }
        public int FieldId { get; set; }
        public int FieldTypeId { get; set; }
        [StringLength(1000)]
        public string Value { get; set; } = default!;
    }
}

