// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Data.ResultTypes
{
    public partial class PH_Workflow_sp_GetPushReportEmailsResult
    {
        [StringLength(200)]
        public string? emailAddress { get; set; }
    }
}

