// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class PhField
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public virtual ICollection<PhFormField> PhFormFields { get; set; } = new List<PhFormField>();

    public virtual ICollection<PhFormValue> PhFormValues { get; set; } = new List<PhFormValue>();

    public virtual ICollection<RptPhUserQueryOutputField> RptPhUserQueryOutputFields { get; set; } = new List<RptPhUserQueryOutputField>();
}
