// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class PrintDocument
{
    public short Docid { get; set; }

    public string DocName { get; set; } = null!;

    public string Filename { get; set; } = null!;

    public string Filetype { get; set; } = null!;

    public short? Compo { get; set; }

    public string? SpGetdata { get; set; }

    public int? FormFieldParserId { get; set; }

    public virtual PrintDocumentFormFieldParser? FormFieldParser { get; set; }
}
