// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Data.ResultTypes
{
    public partial class print_sp_GetDocumentDetailsResult
    {
        public short docid { get; set; }
        [StringLength(50)]
        public string doc_name { get; set; } = default!;
        [StringLength(50)]
        public string filename { get; set; } = default!;
        [StringLength(20)]
        public string filetype { get; set; } = default!;
        public short? compo { get; set; }
        [StringLength(50)]
        public string? sp_getdata { get; set; }
        public int? FormFieldParserId { get; set; }
    }
}

