// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class ReminderEmailSetting
{
    public int Id { get; set; }

    public byte WorkflowId { get; set; }

    public int WsId { get; set; }

    public long Compo { get; set; }

    public byte GroupId { get; set; }

    public int TemplateId { get; set; }

    public int IntervalTime { get; set; }

    public virtual CoreUserGroup Group { get; set; } = null!;

    public virtual ICollection<ReminderEmail> ReminderEmails { get; set; } = new List<ReminderEmail>();

    public virtual CoreEmailTemplate Template { get; set; } = null!;

    public virtual CoreWorkflow Workflow { get; set; } = null!;

    public virtual CoreWorkStatus Ws { get; set; } = null!;
}
