// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class ReminderInactiveSetting
{
    public int IId { get; set; }

    public int Interval { get; set; }

    public int NotificationInterval { get; set; }

    public int TemplateId { get; set; }

    public bool? Active { get; set; }
}
