// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.ResultTypes;

public partial class ReportUnitMetric
{
    public int CsId { get; set; }

    public int? MedTechCount { get; set; }

    public int? MedOfficerCount { get; set; }

    public int? UnitCount { get; set; }

    public int? WingJacount { get; set; }

    public int? WindCccount { get; set; }

    public int? InvCount { get; set; }

    public int? BoardCount { get; set; }
}
