// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Data.ResultTypes
{
    public partial class utility_workflow_sp_InsertPageResult
    {
        public short pageId { get; set; }
        [StringLength(50)]
        public string title { get; set; } = default!;
    }
}

