// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Data.ResultTypes
{
    public partial class workstatus_sp_GetWorkstatusTypesResult
    {
        public int? workstatusId { get; set; }
        public int? workstatusType { get; set; }
        [StringLength(50)]
        public string typeName { get; set; } = default!;
    }
}
