// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class AfrcOracleDbaUsersDatum
{
    public string? Username { get; set; }

    public string? UserId { get; set; }

    public string? Password { get; set; }

    public string? AccountStatus { get; set; }

    public string? LockDate { get; set; }

    public string? ExpiryDate { get; set; }

    public string? DefaultTablespace { get; set; }

    public string? TemporaryTablespace { get; set; }

    public string? Created { get; set; }

    public string? Profile { get; set; }
}
