// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class AfrcOracleLirPersonnelDatum
{
    public string? LiId { get; set; }

    public string? LirId { get; set; }

    public string? Name { get; set; }

    public string? Ssn { get; set; }

    public string? Grade { get; set; }

    public string? LodInvestigationYn { get; set; }

    public string? CreatedBy { get; set; }

    public string? CreatedDate { get; set; }

    public string? ModifiedBy { get; set; }

    public string? ModifiedDate { get; set; }
}
