// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class AlodArcnetRaw
{
    public string? Ssn { get; set; }

    public string? Edipi { get; set; }

    public string? CompletionDate { get; set; }

    public string? DueDate { get; set; }
}
