// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class ApplicationWarmupProcess
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public bool Active { get; set; }

    public virtual ICollection<ApplicationWarmupProcessLog> ApplicationWarmupProcessLogs { get; set; } = new List<ApplicationWarmupProcessLog>();
}
