// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class AspstateTempApplication
{
    public int AppId { get; set; }

    public string AppName { get; set; } = null!;
}
