// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents a parent-level dialogue comment that can have threaded child replies.
/// </summary>
/// <remarks>
/// Dialogue comments support collaborative discussion threads within cases, allowing multiple users
/// to have threaded conversations about specific aspects of a case. Each dialogue comment can have
/// multiple child replies, creating a nested discussion structure.
/// </remarks>
public partial class CaseDialogueComment
{
    public int Id { get; set; }

    public int Lodid { get; set; }

    public string Comments { get; set; } = null!;

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool Deleted { get; set; }

    public int ModuleId { get; set; }

    public int CommentType { get; set; }

    public string? Role { get; set; }

    public virtual ICollection<ChildCaseComment> ChildCaseComments { get; set; } = new List<ChildCaseComment>();
}
