// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CaseDialogueComment
{
    public int Id { get; set; }

    public int Lodid { get; set; }

    public string Comments { get; set; } = null!;

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool Deleted { get; set; }

    public int ModuleId { get; set; }

    public int CommentType { get; set; }

    public string? Role { get; set; }

    public virtual ICollection<ChildCaseComment> ChildCaseComments { get; set; } = new List<ChildCaseComment>();
}
