// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents a hierarchical chain of command in the military organizational structure.
/// </summary>
/// <remarks>
/// <para>
/// Command chains define parent-child relationships between military units, supporting multiple
/// chain types (administrative, operational, medical) and hierarchical navigation for case routing
/// and approval workflows.
/// </para>
/// <para>
/// Chain types include:
/// - Administrative: Normal chain of command for personnel actions
/// - Operational: Combat/mission-focused chain
/// - Medical: Medical treatment facility hierarchy
/// </para>
/// </remarks>
public partial class CommandStructChain
{
    public int CscId { get; set; }

    public int? CsId { get; set; }

    public string? ChainType { get; set; }

    public int? CscIdParent { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public byte ViewType { get; set; }

    public bool? UserModified { get; set; }

    public virtual CoreLkupChainType ViewTypeNavigation { get; set; } = null!;
}
