// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreKeyValKeyType
{
    public int Id { get; set; }

    public string TypeName { get; set; } = null!;

    public virtual ICollection<CoreKeyValKey> CoreKeyValKeys { get; set; } = new List<CoreKeyValKey>();
}
