// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreLkupMilitaryService
{
    public int ServiceId { get; set; }

    public string? Service { get; set; }
}
