// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreLkupCompo
{
    public string Compo { get; set; } = null!;

    public string CompoDescr { get; set; } = null!;

    public string? Abbreviation { get; set; }

    public virtual ICollection<CoreMemoLetterhead> CoreMemoLetterheads { get; set; } = new List<CoreMemoLetterhead>();

    public virtual ICollection<CoreUserGroup> CoreUserGroups { get; set; } = new List<CoreUserGroup>();

    public virtual ICollection<CoreUser> CoreUsers { get; set; } = new List<CoreUser>();
}
