// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreWorkflowView
{
    public byte WorkflowId { get; set; }

    public short PageId { get; set; }

    public virtual CorePage Page { get; set; } = null!;

    public virtual CoreWorkflow Workflow { get; set; } = null!;
}
