// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreLkupFtrecommendation
{
    public int Id { get; set; }

    public string Abbrev { get; set; } = null!;

    public string Description { get; set; } = null!;
}
