// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreLkupFromLocation
{
    public int LocationId { get; set; }

    public string LocationDescription { get; set; } = null!;

    public int SortOrder { get; set; }
}
