// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreSignOnlySignature
{
    public int RefId { get; set; }

    public int Workflow { get; set; }

    public string Signature { get; set; } = null!;

    public string SigDate { get; set; } = null!;

    public int? UserId { get; set; }

    public int? Ptype { get; set; }
}
