// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreWorkflowPerm
{
    public byte WorkflowId { get; set; }

    public byte GroupId { get; set; }

    public bool CanView { get; set; }

    public bool CanCreate { get; set; }

    public virtual CoreUserGroup Group { get; set; } = null!;

    public virtual CoreWorkflow Workflow { get; set; } = null!;
}
