// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreUserGroup
{
    public byte GroupId { get; set; }

    public string Name { get; set; } = null!;

    public string Abbr { get; set; } = null!;

    public string Compo { get; set; } = null!;

    public byte AccessScope { get; set; }

    public bool Active { get; set; }

    public bool PartialMatch { get; set; }

    public bool ShowInfo { get; set; }

    public byte SortOrder { get; set; }

    public bool HipaaRequired { get; set; }

    public bool CanRegister { get; set; }

    public byte ReportView { get; set; }

    public int GroupLevel { get; set; }

    public virtual CoreLkupAccessScope AccessScopeNavigation { get; set; } = null!;

    public virtual CoreLkupCompo CompoNavigation { get; set; } = null!;

    public virtual ICollection<CoreMemoGroup> CoreMemoGroups { get; set; } = new List<CoreMemoGroup>();

    public virtual ICollection<CorePageAccess> CorePageAccesses { get; set; } = new List<CorePageAccess>();

    public virtual ICollection<CoreStatusCode> CoreStatusCodes { get; set; } = new List<CoreStatusCode>();

    public virtual ICollection<CoreUserRole> CoreUserRoles { get; set; } = new List<CoreUserRole>();

    public virtual ICollection<Form348Sarc> Form348Sarcs { get; set; } = new List<Form348Sarc>();

    public virtual CoreUserGroupLevel GroupLevelNavigation { get; set; } = null!;

    public virtual ICollection<ReminderEmailSetting> ReminderEmailSettings { get; set; } = new List<ReminderEmailSetting>();

    public virtual CoreLkupChainType ReportViewNavigation { get; set; } = null!;
}
