// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreWorkStatusValidation
{
    public int WsvId { get; set; }

    public int WsId { get; set; }

    public short ValidationType { get; set; }

    public string Data { get; set; } = null!;

    public bool Active { get; set; }

    public virtual CoreWorkStatus Ws { get; set; } = null!;
}
