// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreWorkflowMemberComponent
{
    public byte WorkflowId { get; set; }

    public int ComponentId { get; set; }

    public virtual CoreLkupComponent Component { get; set; } = null!;

    public virtual CoreWorkflow Workflow { get; set; } = null!;
}
