// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreWorkStatusUpdated
{
    public int WsId { get; set; }

    public byte WorkflowId { get; set; }

    public byte StatusId { get; set; }

    public byte SortOrder { get; set; }
}
