// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreLkupMedicalFacility
{
    public int FacilityId { get; set; }

    public string FacilityDescription { get; set; } = null!;

    public int SortOrder { get; set; }

    public string? FacilityType { get; set; }
}
