// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreLkupComponent
{
    public int ComponentId { get; set; }

    public string ComponentDescription { get; set; } = null!;

    public int SortOrder { get; set; }
}
