// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreLogEmail
{
    public int EId { get; set; }

    public int? UserId { get; set; }

    public DateTime? DateSent { get; set; }

    public string? ETo { get; set; }

    public string? ECc { get; set; }

    public string? EBcc { get; set; }

    public string? Subject { get; set; }

    public string? Body { get; set; }

    public string? Failed { get; set; }

    public int? TemplateId { get; set; }
}
