// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreUser
{
    public int UserId { get; set; }

    public string? Edipin { get; set; }

    public string Username { get; set; } = null!;

    public string LastName { get; set; } = null!;

    public string FirstName { get; set; } = null!;

    public string? MiddleName { get; set; }

    public string? Title { get; set; }

    public string? Ssn { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public string? Phone { get; set; }

    public string? Dsn { get; set; }

    public string? Email { get; set; }

    public string WorkCompo { get; set; } = null!;

    public byte AccessStatus { get; set; }

    public bool ReceiveEmail { get; set; }

    public DateTime ExpirationDate { get; set; }

    public string? Comment { get; set; }

    public DateTime? LastAccessDate { get; set; }

    public int RankCode { get; set; }

    public string? WorkStreet { get; set; }

    public string? WorkCity { get; set; }

    public string? WorkState { get; set; }

    public string? WorkZip { get; set; }

    public string? WorkCountry { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public int CsId { get; set; }

    public int? AdaCsId { get; set; }

    public int? CurrentRole { get; set; }

    public DateTime? DisabledDate { get; set; }

    public string? Email2 { get; set; }

    public string? Email3 { get; set; }

    public byte? ReportView { get; set; }

    public byte? DisabledBy { get; set; }

    public byte UnitView { get; set; }

    public bool ReceiveReminderEmail { get; set; }

    public string? Edipin2 { get; set; }

    public short? IsPinActive { get; set; }

    public virtual CoreLkupAccessStatus AccessStatusNavigation { get; set; } = null!;

    public virtual CommandStruct? AdaCs { get; set; }

    public virtual ICollection<CoreLogAction> CoreLogActions { get; set; } = new List<CoreLogAction>();

    public virtual ICollection<CoreMemoContent> CoreMemoContents { get; set; } = new List<CoreMemoContent>();

    public virtual ICollection<CoreMemoContents2> CoreMemoContents2s { get; set; } = new List<CoreMemoContents2>();

    public virtual ICollection<CoreMemoTemplate> CoreMemoTemplateCreatedByNavigations { get; set; } = new List<CoreMemoTemplate>();

    public virtual ICollection<CoreMemoTemplate> CoreMemoTemplateModifiedByNavigations { get; set; } = new List<CoreMemoTemplate>();

    public virtual ICollection<CoreMemo> CoreMemos { get; set; } = new List<CoreMemo>();

    public virtual ICollection<CoreMemos2> CoreMemos2s { get; set; } = new List<CoreMemos2>();

    public virtual ICollection<CoreUserRole> CoreUserRoles { get; set; } = new List<CoreUserRole>();

    public virtual ICollection<CoreWorkStatusTracking> CoreWorkStatusTrackings { get; set; } = new List<CoreWorkStatusTracking>();

    public virtual ICollection<CoreWorkflowLock> CoreWorkflowLocks { get; set; } = new List<CoreWorkflowLock>();

    public virtual CommandStruct Cs { get; set; } = null!;

    public virtual CoreUserRole? CurrentRoleNavigation { get; set; }

    public virtual ICollection<Form348ApFinding> Form348ApFindingCreatedByNavigations { get; set; } = new List<Form348ApFinding>();

    public virtual ICollection<Form348ApFinding> Form348ApFindingModifiedByNavigations { get; set; } = new List<Form348ApFinding>();

    public virtual ICollection<Form348ApSarcFinding> Form348ApSarcFindingCreatedByNavigations { get; set; } = new List<Form348ApSarcFinding>();

    public virtual ICollection<Form348ApSarcFinding> Form348ApSarcFindingModifiedByNavigations { get; set; } = new List<Form348ApSarcFinding>();

    public virtual ICollection<Form348> Form348AppAuthUsers { get; set; } = new List<Form348>();

    public virtual ICollection<Form348> Form348CreatedByNavigations { get; set; } = new List<Form348>();

    public virtual ICollection<Form348Finding> Form348FindingCreatedByNavigations { get; set; } = new List<Form348Finding>();

    public virtual ICollection<Form348Finding> Form348FindingModifiedByNavigations { get; set; } = new List<Form348Finding>();

    public virtual ICollection<Form348> Form348ModifiedByNavigations { get; set; } = new List<Form348>();

    public virtual ICollection<Form348RrFinding> Form348RrFindingCreatedByNavigations { get; set; } = new List<Form348RrFinding>();

    public virtual ICollection<Form348RrFinding> Form348RrFindingModifiedByNavigations { get; set; } = new List<Form348RrFinding>();

    public virtual ICollection<Form348SarcFinding> Form348SarcFindingCreatedByNavigations { get; set; } = new List<Form348SarcFinding>();

    public virtual ICollection<Form348SarcFinding> Form348SarcFindingModifiedByNavigations { get; set; } = new List<Form348SarcFinding>();

    public virtual ICollection<Form348Sarc> Form348Sarcs { get; set; } = new List<Form348Sarc>();

    public virtual ICollection<Form348Sc> Form348ScCreatedByNavigations { get; set; } = new List<Form348Sc>();

    public virtual ICollection<Form348Sc> Form348ScModifiedByNavigations { get; set; } = new List<Form348Sc>();

    public virtual ICollection<CoreUser> InverseModifiedByNavigation { get; set; } = new List<CoreUser>();

    public virtual CoreUser? ModifiedByNavigation { get; set; }

    public virtual CoreLkupGrade RankCodeNavigation { get; set; } = null!;

    public virtual CoreLkupChainType? ReportViewNavigation { get; set; }

    public virtual ICollection<RptUserQuery> RptUserQueries { get; set; } = new List<RptUserQuery>();

    public virtual CoreLkupCompo WorkCompoNavigation { get; set; } = null!;
}
