// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class CoreCaseTypeSubCaseTypeMap
{
    public int CaseTypeId { get; set; }

    public int SubCaseTypeId { get; set; }

    public virtual CoreCaseType CaseType { get; set; } = null!;

    public virtual CoreSubCaseType SubCaseType { get; set; } = null!;
}
