// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreLkupRwoareason
{
    public byte Id { get; set; }

    public string Description { get; set; } = null!;

    public string Type { get; set; } = null!;

    public virtual ICollection<Form348Sarc> Form348Sarcs { get; set; } = new List<Form348Sarc>();

    public virtual ICollection<Form348Sc> Form348Scs { get; set; } = new List<Form348Sc>();

    public virtual ICollection<Form348> Form348s { get; set; } = new List<Form348>();
}
