// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents an action option available to users when a case is in a specific workflow status.
/// </summary>
/// <remarks>
/// Status options define the user-facing actions that can be performed on a case in a particular
/// workflow status. Each option includes display text shown to users, a target status that the
/// case will transition to, and configuration for sort order and availability.
/// 
/// The Template field specifies which form or template to display when the action is selected.
/// The Compo field allows component-specific options (e.g., different actions for Active vs Reserve).
/// The Active flag enables options to be temporarily disabled without removing them.
/// 
/// Status options are linked to workflow actions via CoreWorkStatusAction, which defines the
/// specific behavior when the option is selected. This separation allows the same display option
/// to trigger different actions based on business rules.
/// </remarks>
public partial class CoreWorkStatusOption
{
    public int WsoId { get; set; }

    public int WsId { get; set; }

    public string DisplayText { get; set; } = null!;

    public bool Active { get; set; }

    public byte SortOrder { get; set; }

    public byte Template { get; set; }

    public int WsIdOut { get; set; }

    public int? Compo { get; set; }

    public virtual ICollection<CoreWorkStatusAction> CoreWorkStatusActions { get; set; } = new List<CoreWorkStatusAction>();

    public virtual ICollection<CoreWorkStatusRule> CoreWorkStatusRules { get; set; } = new List<CoreWorkStatusRule>();

    public virtual CoreWorkStatus Ws { get; set; } = null!;

    public virtual CoreWorkStatus WsIdOutNavigation { get; set; } = null!;
}
