// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreUserPermission
{
    public int UserId { get; set; }

    public short PermId { get; set; }

    public string Status { get; set; } = null!;

    public virtual CorePermission Perm { get; set; } = null!;

    public virtual CoreUser User { get; set; } = null!;
}
