// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreLkupModule
{
    public byte ModuleId { get; set; }

    public string ModuleName { get; set; } = null!;

    public bool IsSpecialCase { get; set; }

    public virtual ICollection<CoreLogAction> CoreLogActions { get; set; } = new List<CoreLogAction>();

    public virtual ICollection<CoreMemoTemplate> CoreMemoTemplates { get; set; } = new List<CoreMemoTemplate>();

    public virtual ICollection<CoreStatusCode> CoreStatusCodes { get; set; } = new List<CoreStatusCode>();

    public virtual ICollection<CoreWorkStatusTracking> CoreWorkStatusTrackings { get; set; } = new List<CoreWorkStatusTracking>();

    public virtual ICollection<CoreWorkflowLock> CoreWorkflowLocks { get; set; } = new List<CoreWorkflowLock>();

    public virtual ICollection<CoreWorkflow> CoreWorkflows { get; set; } = new List<CoreWorkflow>();

    public virtual ICollection<Form348Sc> Form348Scs { get; set; } = new List<Form348Sc>();
}
