// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents a memorandum attached to a case for official correspondence and documentation.
/// </summary>
/// <remarks>
/// CoreMemo stores official memoranda that document case actions, decisions, and communications.
/// Each memo is generated from a template (CoreMemoTemplate) and includes formatted letterhead
/// (CoreMemoLetterhead) for official presentation.
/// 
/// Memos are linked to cases via RefId and can contain multiple content sections stored in
/// CoreMemoContent. The Deleted flag supports soft deletion, allowing memos to be hidden
/// without losing historical records. This is important for audit trails and compliance.
/// 
/// Memos serve as official documentation for case decisions, approvals, notifications, and
/// correspondence with service members, commanders, and medical providers.
/// </remarks>
public partial class CoreMemo
{
    public int MemoId { get; set; }

    public int RefId { get; set; }

    public byte TemplateId { get; set; }

    public bool Deleted { get; set; }

    public byte LetterHead { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<CoreMemoContent> CoreMemoContents { get; set; } = new List<CoreMemoContent>();

    public virtual CoreUser CreatedByNavigation { get; set; } = null!;

    public virtual CoreMemoLetterhead LetterHeadNavigation { get; set; } = null!;

    public virtual CoreMemoTemplate Template { get; set; } = null!;
}
