// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreSignatureMetaDatum
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public byte WorkflowId { get; set; }

    public int WorkStatus { get; set; }

    public byte UserGroup { get; set; }

    public int UserId { get; set; }

    public DateTime Date { get; set; }

    public string NameAndRank { get; set; } = null!;

    public string? Title { get; set; }

    public virtual CoreUser User { get; set; } = null!;

    public virtual CoreUserGroup UserGroupNavigation { get; set; } = null!;

    public virtual CoreWorkStatus WorkStatusNavigation { get; set; } = null!;

    public virtual CoreWorkflow Workflow { get; set; } = null!;
}
