// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreUserRoleRequest
{
    public int Id { get; set; }

    public byte Status { get; set; }

    public int UserId { get; set; }

    public byte RequestedGroupId { get; set; }

    public byte? ExistingGroupId { get; set; }

    public bool NewRole { get; set; }

    public string? RequestorComment { get; set; }

    public DateTime RequestedDate { get; set; }

    public int? CompletedBy { get; set; }

    public DateTime? CompletedDate { get; set; }

    public string? CompletedComment { get; set; }

    public virtual CoreUser? CompletedByNavigation { get; set; }

    public virtual CoreUserGroup? ExistingGroup { get; set; }

    public virtual CoreUserGroup RequestedGroup { get; set; } = null!;

    public virtual CoreLkupAccessStatus StatusNavigation { get; set; } = null!;

    public virtual CoreUser User { get; set; } = null!;
}
