// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreLkupWorkflowAction
{
    public byte Type { get; set; }

    public string Text { get; set; } = null!;

    public virtual ICollection<CoreWorkStatusAction> CoreWorkStatusActions { get; set; } = new List<CoreWorkStatusAction>();
}
