// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents a military pay grade/rank in the Electronic Case Tracking system.
/// </summary>
/// <remarks>
/// This lookup table defines military pay grades and ranks used throughout the system
/// for member identification and organizational hierarchy. Includes enlisted grades
/// (E-1 through E-9), officer grades (O-1 through O-10), warrant officer grades
/// (W-1 through W-5), and civilian grade equivalents.
/// 
/// Pay grades are used to:
/// - Identify service members in case records
/// - Display rank information in user interfaces
/// - Determine approval authorities based on grade/rank
/// - Sort and filter members by seniority
/// - Generate reports organized by grade/rank
/// 
/// The Displayorder field determines the sort order for displaying grades, typically
/// from lowest to highest rank. The Title field contains the formal rank title
/// (e.g., "Private", "Sergeant", "Lieutenant", "Captain"), while Grade contains
/// the pay grade code (e.g., "E-1", "E-5", "O-1", "O-3").
/// </remarks>
public partial class CoreLkupGrade
{
    public int Code { get; set; }

    public string? Rank { get; set; }

    public string? Grade { get; set; }

    public string? Title { get; set; }

    public short? Displayorder { get; set; }

    public virtual ICollection<CoreUser> CoreUsers { get; set; } = new List<CoreUser>();

    public virtual ICollection<CoreWorkStatusTracking> CoreWorkStatusTrackings { get; set; } = new List<CoreWorkStatusTracking>();

    public virtual ICollection<Form348ApSarc> Form348ApSarcs { get; set; } = new List<Form348ApSarc>();

    public virtual ICollection<Form348Ap> Form348Aps { get; set; } = new List<Form348Ap>();

    public virtual ICollection<Form348Rr> Form348Rrs { get; set; } = new List<Form348Rr>();

    public virtual ICollection<Form348Sarc> Form348Sarcs { get; set; } = new List<Form348Sarc>();

    public virtual ICollection<Form348> Form348s { get; set; } = new List<Form348>();

    public virtual ICollection<GradeAbbreviation> GradeAbbreviations { get; set; } = new List<GradeAbbreviation>();

    public virtual ICollection<MemberDatum> MemberData { get; set; } = new List<MemberDatum>();
}
