// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

/// <summary>
/// Represents a module type in the Electronic Case Tracking system.
/// </summary>
/// <remarks>
/// This lookup table defines the available modules (workflow types) in the ECT system,
/// such as LOD (Line of Duty), IDES (Integrated Disability Evaluation System),
/// PDES (Physical Disability Evaluation System), etc. Each module represents a distinct
/// case management workflow with specific forms, processes, business rules, and approval chains.
/// 
/// Modules are foundational to the system architecture - they determine:
/// - Which forms are available for case creation
/// - What workflow states and transitions are valid
/// - Which business rules apply to case processing
/// - How cases are routed through approval chains
/// - What reports and metrics are generated
/// 
/// The IsSpecialCase flag indicates whether the module requires special handling or
/// has unique processing requirements beyond standard workflow logic.
/// </remarks>
public partial class CoreLkupModule
{
    public byte ModuleId { get; set; }

    public string ModuleName { get; set; } = null!;

    public bool IsSpecialCase { get; set; }

    public virtual ICollection<CoreLogAction> CoreLogActions { get; set; } = new List<CoreLogAction>();

    public virtual ICollection<CoreMemoTemplate> CoreMemoTemplates { get; set; } = new List<CoreMemoTemplate>();

    public virtual ICollection<CoreStatusCode> CoreStatusCodes { get; set; } = new List<CoreStatusCode>();

    public virtual ICollection<CoreWorkStatusTracking> CoreWorkStatusTrackings { get; set; } = new List<CoreWorkStatusTracking>();

    public virtual ICollection<CoreWorkflowLock> CoreWorkflowLocks { get; set; } = new List<CoreWorkflowLock>();

    public virtual ICollection<CoreWorkflow> CoreWorkflows { get; set; } = new List<CoreWorkflow>();

    public virtual ICollection<Form348Sc> Form348Scs { get; set; } = new List<Form348Sc>();
}
