// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class CoreUsersAltTitle
{
    public int UserId { get; set; }

    public int GroupId { get; set; }

    public string? Title { get; set; }
}
