// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class DataElementDetail
{
    public int DataElementId { get; set; }

    public string DataElementName { get; set; } = null!;

    public string DataElementType { get; set; } = null!;

    public string DataType { get; set; } = null!;

    public string DataPurpose { get; set; } = null!;

    public string EntityPurpose { get; set; } = null!;

    public string DatabaseServer { get; set; } = null!;

    public string DatabaseName { get; set; } = null!;

    public string SchemaName { get; set; } = null!;

    public string TableName { get; set; } = null!;

    public string ColumnName { get; set; } = null!;

    public string OriginalDataSource { get; set; } = null!;

    public string Notes { get; set; } = null!;

    public string? ForeignKeyTo { get; set; }

    public long RowCount { get; set; }

    public DateTime? DataStartTime { get; set; }

    public DateTime? DataEndTime { get; set; }

    public DateTime? CreateTime { get; set; }

    public DateTime LastUpdateTime { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsNullable { get; set; }
}
