// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class Form348PostProcessing
{
    public int LodId { get; set; }

    public string? HelpExtensionNumber { get; set; }

    public string? AppealStreet { get; set; }

    public string? AppealCity { get; set; }

    public string? AppealState { get; set; }

    public string? AppealZip { get; set; }

    public string? AppealCountry { get; set; }

    public string? NokFirstName { get; set; }

    public string? NokLastName { get; set; }

    public string? NokMiddleName { get; set; }

    public DateTime? NotificationDate { get; set; }

    public string? Email { get; set; }

    public int? AddressFlag { get; set; }

    public int? EmailFlag { get; set; }

    public int? PhoneFlag { get; set; }

    public virtual Form348 Lod { get; set; } = null!;
}
