// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class Form348PscdFinding
{
    public int Id { get; set; }

    public int PscdId { get; set; }

    public string? Name { get; set; }

    public short? Ptype { get; set; }

    public string? Remarks { get; set; }

    public byte? Finding { get; set; }

    public string? FindingText { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string? AdditionalRemarks { get; set; }

    public bool? ReferToDes { get; set; }

    public virtual Form348Sc Pscd { get; set; } = null!;
}
