// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class Form261
{
    public int LodId { get; set; }

    public DateTime? ReportDate { get; set; }

    public byte? InvestigationOf { get; set; }

    public byte? Status { get; set; }

    public string? InactiveDutyTraining { get; set; }

    public DateTime? DurationStartDate { get; set; }

    public DateTime? DurationFinishDate { get; set; }

    public int? IoUserId { get; set; }

    public string? OtherPersonnels { get; set; }

    public byte? FinalApprovalFindings { get; set; }

    public DateTime? FindingsDate { get; set; }

    public string? Place { get; set; }

    public string? HowSustained { get; set; }

    public string? MedicalDiagnosis { get; set; }

    public bool? PresentForDuty { get; set; }

    public bool? AbsentWithAuthority { get; set; }

    public bool? IntentionalMisconduct { get; set; }

    public bool? MentallySound { get; set; }

    public string? Remarks { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public DateTime? SigDateIo { get; set; }

    public string? SigInfoIo { get; set; }

    public DateTime? SigDateAppointing { get; set; }

    public string? SigInfoAppointing { get; set; }

    public virtual CoreLkUpFinding? FinalApprovalFindingsNavigation { get; set; }
}
