// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class Form348Audit
{
    public int AuditId { get; set; }

    public int LodId { get; set; }

    public string CaseId { get; set; } = null!;

    public int Workflow { get; set; }

    public short? MedicallyAppropriate { get; set; }

    public bool? SgDx { get; set; }

    public bool? SgIsupport { get; set; }

    public bool? SgEpts { get; set; }

    public bool? SgAggravation { get; set; }

    public bool? SgPrinciples { get; set; }

    public string? SgOther { get; set; }

    public short? SgProofApplied { get; set; }

    public short? SgCorrectStandard { get; set; }

    public short? SgProofMet { get; set; }

    public short? SgEvidence { get; set; }

    public short? SgMisconduct { get; set; }

    public short? SgFormalInvestigation { get; set; }

    public short? LegallySufficient { get; set; }

    public bool? JaStandardOfProof { get; set; }

    public bool? JaDeathAndMva { get; set; }

    public bool? JaFormalPolicy { get; set; }

    public bool? JaAfi { get; set; }

    public string? JaOther { get; set; }

    public short? JaProofApplied { get; set; }

    public short? JaCorrectStandard { get; set; }

    public short? JaProofMet { get; set; }

    public short? JaEvidence { get; set; }

    public short? JaMisconduct { get; set; }

    public short? JaFormalInvestigation { get; set; }

    public short? StatusValidated { get; set; }

    public bool? StatusOfMember { get; set; }

    public bool? Orders { get; set; }

    public bool? A1Epts { get; set; }

    public bool? Idt { get; set; }

    public bool? Pcars { get; set; }

    public bool? EightYearRule { get; set; }

    public string? A1Other { get; set; }

    public short? Lodinitiation { get; set; }

    public short? WrittenDiagnosis { get; set; }

    public short? MemberRequest { get; set; }

    public short? IncurredOrAggravated { get; set; }

    public short? IllnessOrDisease { get; set; }

    public int? Activites { get; set; }

    public string? A1Comment { get; set; }

    public string? JaComment { get; set; }

    public string? SgComment { get; set; }

    public int? Determination { get; set; }

    public int? A1DeterminationNotCorrect { get; set; }
}
