// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class Form348ApprovalAuthority
{
    public byte Id { get; set; }

    public string Name { get; set; } = null!;

    public string SigBlock { get; set; } = null!;

    public string Title { get; set; } = null!;

    public DateTime EffectiveDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public int ModifiedBy { get; set; }

    public DateTime ModifiedDate { get; set; }
}
