// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class Form348ApFinding
{
    public int Id { get; set; }

    public int AppealId { get; set; }

    public short Ptype { get; set; }

    public string? LastName { get; set; }

    public string? FirstName { get; set; }

    public string? MiddleName { get; set; }

    public string? Grade { get; set; }

    public string? Rank { get; set; }

    public string? Compo { get; set; }

    public string? Pascode { get; set; }

    public byte? Finding { get; set; }

    public string? Explanation { get; set; }

    public bool IsLegacyFinding { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public int ModifiedBy { get; set; }

    public DateTime ModifiedDate { get; set; }

    public string? Concur { get; set; }

    public virtual Form348Ap Appeal { get; set; } = null!;

    public virtual CoreUser CreatedByNavigation { get; set; } = null!;

    public virtual CoreUser ModifiedByNavigation { get; set; } = null!;

    public virtual CoreLkupPersonnelType PtypeNavigation { get; set; } = null!;
}
