// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class Form348IncapAppeal
{
    public int ApId { get; set; }

    public int ScId { get; set; }

    public int? ExtId { get; set; }

    public bool? WccAppealApproval { get; set; }

    public bool? OprAppealApproval { get; set; }

    public bool? OcrAppealApproval { get; set; }

    public bool? DosAppealApproval { get; set; }

    public bool? CcrAppealApproval { get; set; }

    public bool? VcrAppealApproval { get; set; }

    public bool? DopAppealApproval { get; set; }

    public bool? CafrAppealApproval { get; set; }

    public virtual Form348IncapFinding Sc { get; set; } = null!;
}
