// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class Form348Rr
{
    public int RequestId { get; set; }

    public int? ReinvestigationLodId { get; set; }

    public int InitialLodId { get; set; }

    public string CaseId { get; set; } = null!;

    public int CreatedBy { get; set; }

    public DateOnly CreatedDate { get; set; }

    public int? Workflow { get; set; }

    public int? Status { get; set; }

    public byte? RwoaReason { get; set; }

    public DateTime? RwoaDate { get; set; }

    public string? RwoaExplanation { get; set; }

    public DateTime? SigDateMpf { get; set; }

    public string? SigNameMpf { get; set; }

    public string? SigTitleMpf { get; set; }

    public DateTime? SigDateWingJa { get; set; }

    public string? SigNameWingJa { get; set; }

    public string? SigTitleWingJa { get; set; }

    public DateTime? SigDateWingCc { get; set; }

    public string? SigNameWingCc { get; set; }

    public string? SigTitleWingCc { get; set; }

    public DateTime? SigDateBoardAdmin { get; set; }

    public string? SigNameBoardAdmin { get; set; }

    public string? SigTitleBoardAdmin { get; set; }

    public DateTime? SigDateBoardMedical { get; set; }

    public string? SigNameBoardMedical { get; set; }

    public string? SigTitleBoardMedical { get; set; }

    public DateTime? SigDateBoardLegal { get; set; }

    public string? SigNameBoardLegal { get; set; }

    public string? SigTitleBoardLegal { get; set; }

    public DateTime? SigDateApproval { get; set; }

    public string? SigNameApproval { get; set; }

    public string? SigTitleApproval { get; set; }

    public DateTime? SigDateBoardTechFinal { get; set; }

    public string? SigNameBoardTechFinal { get; set; }

    public string? SigTitleBoardTechFinal { get; set; }

    public byte? WingCcApproved { get; set; }

    public byte? BoardMedicalApproved { get; set; }

    public byte? BoardLegalApproved { get; set; }

    public byte? AaFinalApproved { get; set; }

    public string? ReturnComment { get; set; }

    public string? MemberSsn { get; set; }

    public byte? WingJaApproved { get; set; }

    public byte? BoardTechApproval1 { get; set; }

    public byte? BoardTechApproval2 { get; set; }

    public string? WingJaApprovalComment { get; set; }

    public string? WingCcApprovalComment { get; set; }

    public string? BoardTechApproval1Comment { get; set; }

    public string? BoardMedicalApprovalComment { get; set; }

    public string? BoardLegalApprovalComment { get; set; }

    public string? AaFinalApprovalComment { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? DocGroupId { get; set; }

    public string? MemberName { get; set; }

    public int? CancelReason { get; set; }

    public string? CancelExplanation { get; set; }

    public DateTime? CancelDate { get; set; }

    public int? ReturnToGroup { get; set; }

    public int? ReturnByGroup { get; set; }

    public string? SigNameLodPm { get; set; }

    public DateTime? SigDateLodPm { get; set; }

    public string? SigTitleLodPm { get; set; }

    public string? SigNameBoardA1 { get; set; }

    public DateTime? SigDateBoardA1 { get; set; }

    public string? SigTitleBoardA1 { get; set; }

    public byte? BoardA1Approved { get; set; }

    public string? BoardA1ApprovalComment { get; set; }

    public string MemberUnit { get; set; } = null!;

    public int MemberUnitId { get; set; }

    public string MemberCompo { get; set; } = null!;

    public int MemberGrade { get; set; }

    public bool IsNonDbsignCase { get; set; }

    public virtual ICollection<Form348RrFinding> Form348RrFindings { get; set; } = new List<Form348RrFinding>();

    public virtual CoreLkupGrade MemberGradeNavigation { get; set; } = null!;
}
