// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class Form348Sarc
{
    public int SarcId { get; set; }

    public string CaseId { get; set; } = null!;

    public int Status { get; set; }

    public byte? Workflow { get; set; }

    public string MemberName { get; set; } = null!;

    public string MemberSsn { get; set; } = null!;

    public int MemberGrade { get; set; }

    public string MemberUnit { get; set; } = null!;

    public int MemberUnitId { get; set; }

    public DateTime? MemberDob { get; set; }

    public string MemberCompo { get; set; } = null!;

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public int? DocGroupId { get; set; }

    public DateTime? IncidentDate { get; set; }

    public int? DutyStatus { get; set; }

    public DateTime? DurationStartDate { get; set; }

    public DateTime? DurationEndDate { get; set; }

    public bool? IcdE9688 { get; set; }

    public bool? IcdE9699 { get; set; }

    public bool? IcdOther { get; set; }

    public bool? InDutyStatus { get; set; }

    public DateTime? SigDateRslWingSarc { get; set; }

    public string? SigNameRslWingSarc { get; set; }

    public string? SigTitleRslWingSarc { get; set; }

    public DateTime? SigDateSarcA1 { get; set; }

    public string? SigNameSarcA1 { get; set; }

    public string? SigTitleSarcA1 { get; set; }

    public DateTime? SigDateBoardMedical { get; set; }

    public string? SigNameBoardMedical { get; set; }

    public string? SigTitleBoardMedical { get; set; }

    public DateTime? SigDateBoardJa { get; set; }

    public string? SigNameBoardJa { get; set; }

    public string? SigTitleBoardJa { get; set; }

    public DateTime? SigDateBoardAdmin { get; set; }

    public string? SigNameBoardAdmin { get; set; }

    public string? SigTitleBoardAdmin { get; set; }

    public DateTime? SigDateApproving { get; set; }

    public string? SigNameApproving { get; set; }

    public string? SigTitleApproving { get; set; }

    public byte? RwoaReason { get; set; }

    public string? RwoaExplanation { get; set; }

    public DateTime? RwoaDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? CancelReason { get; set; }

    public string? CancelExplanation { get; set; }

    public DateTime? CancelDate { get; set; }

    public string? DefSexAssaultDbCaseNum { get; set; }

    public int? ReturnToGroup { get; set; }

    public int? ReturnByGroup { get; set; }

    public byte? ConsultationFromUsergroupId { get; set; }

    public string? ReturnComment { get; set; }

    public bool IsPostProcessingComplete { get; set; }

    public virtual CoreUserGroup? ConsultationFromUsergroup { get; set; }

    public virtual CoreUser CreatedByNavigation { get; set; } = null!;

    public virtual ICollection<Form348SarcFinding> Form348SarcFindings { get; set; } = new List<Form348SarcFinding>();

    public virtual ICollection<Form348SarcIcd> Form348SarcIcds { get; set; } = new List<Form348SarcIcd>();

    public virtual Form348SarcPostProcessing? Form348SarcPostProcessing { get; set; }

    public virtual CoreLkupGrade MemberGradeNavigation { get; set; } = null!;

    public virtual CoreLkupRwoareason? RwoaReasonNavigation { get; set; }

    public virtual CoreWorkStatus StatusNavigation { get; set; } = null!;

    public virtual CoreWorkflow? WorkflowNavigation { get; set; }
}
