// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class GradeAbbreviation
{
    public int AbbreviationTypeId { get; set; }

    public int GradeCode { get; set; }

    public string Abbreviation { get; set; } = null!;

    public virtual CoreLkupGradeAbbreviationType AbbreviationType { get; set; } = null!;

    public virtual CoreLkupGrade GradeCodeNavigation { get; set; } = null!;
}
