// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class HyperLinkType
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public virtual ICollection<HyperLink> HyperLinks { get; set; } = new List<HyperLink>();
}
