// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class HyperLink
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public int TypeId { get; set; }

    public string DisplayText { get; set; } = null!;

    public string Value { get; set; } = null!;

    public virtual HyperLinkType Type { get; set; } = null!;
}
