// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class ImpDbaRolePriv
{
    public string? Grantee { get; set; }

    public string? GrantedRole { get; set; }

    public string? Adm { get; set; }

    public string? Def { get; set; }
}
