// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class ImpLkupAccessStatus
{
    public string? Accountstatus { get; set; }

    public byte? StatusId { get; set; }
}
