// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class ImpManpower
{
    public string? PosNbr { get; set; }

    public string? PasCode { get; set; }
}
