// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class ImpPermmapping
{
    public string PermName { get; set; } = null!;

    public int? GroupId { get; set; }
}
