// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class ImpProcmapping
{
    public int PvsId { get; set; }

    public int ProcId { get; set; }

    public int? AlodWorkstatus { get; set; }
}
