// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class ImpUserrole
{
    public string? Username { get; set; }

    public string? Permission { get; set; }

    public int? Groupid { get; set; }

    public bool? IsDefault { get; set; }
}
