// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class ImpUsermapping
{
    public int? UserId { get; set; }

    public int? PersonId { get; set; }

    public string? Username { get; set; }
}
