// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class Lodmapping
{
    public int? AlodLodId { get; set; }

    public int? RcphaLodid { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? RcPhaOrgLodid { get; set; }

    public string? CaseId { get; set; }

    public int? AlodStatus { get; set; }

    public int? RcPhaValidStatus { get; set; }

    public string? RcphaProcName { get; set; }
}
