// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class MemoGroup
{
    public string? Id { get; set; }

    public string? TemplateId { get; set; }

    public string? GroupId { get; set; }

    public string? CanCreate { get; set; }

    public string? CanEdit { get; set; }

    public string? CanDelete { get; set; }

    public string? CanView { get; set; }
}
