// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class PalDataTemp
{
    public int Id { get; set; }

    public string? LastName { get; set; }

    public string? FirstName { get; set; }

    public string? Ssan { get; set; }

    public string? Rank { get; set; }

    public DateTime? BirthDate { get; set; }

    public string? Type { get; set; }

    public string? Rating { get; set; }

    public string? AscCode { get; set; }

    public string? Baseassign { get; set; }

    public string? Completeby { get; set; }

    public string? Disposition { get; set; }

    public string? SentTo { get; set; }

    public DateTime? DateOut { get; set; }

    public DateTime? DateRec { get; set; }

    public string? Fiche { get; set; }

    public DateTime? Expiredate { get; set; }

    public bool? IndefiniteWaiver { get; set; }

    public bool? Wnlr { get; set; }

    public string? Diagnosis { get; set; }

    public string? Remarks { get; set; }

    public bool? Rwoa { get; set; }

    public string? RwoaReason { get; set; }

    public bool? Trwoa { get; set; }

    public string? ReceivedFrom { get; set; }

    public string? HeShe { get; set; }

    public string? HisHer { get; set; }

    public string? HimHer { get; set; }

    public string? RetToDutyBy { get; set; }

    public bool? AlcC { get; set; }

    public bool? AfForm422Feb93Format { get; set; }

    public bool? NarrativeSummary { get; set; }

    public bool? Questionnaire { get; set; }

    public bool? UnitCommanderSMemo { get; set; }

    public bool? IpebElectionIncluded { get; set; }

    public bool? IpebelectedYes { get; set; }

    public bool? IpebelectedNo { get; set; }

    public bool? NoHome { get; set; }

    public bool? AsthmaGen12 { get; set; }

    public bool? Cad121 { get; set; }

    public bool? Dm122 { get; set; }

    public bool? Hiv123 { get; set; }

    public bool? Psych124 { get; set; }

    public bool? HomeStationNoMandays { get; set; }

    public bool? Conus { get; set; }

    public bool? ConusIfCheckedFirst { get; set; }

    public bool? _1 { get; set; }

    public bool? _3 { get; set; }

    public bool? _31 { get; set; }

    public bool? _4 { get; set; }

    public bool? _41 { get; set; }

    public bool? _411 { get; set; }

    public bool? _42 { get; set; }

    public bool? _43 { get; set; }

    public bool? _44 { get; set; }

    public bool? _45 { get; set; }

    public bool? _5 { get; set; }

    public bool? _6 { get; set; }

    public bool? _61 { get; set; }

    public bool? _7 { get; set; }

    public bool? _8 { get; set; }

    public bool? _9 { get; set; }

    public bool? _91 { get; set; }

    public bool? _10 { get; set; }

    public bool? _101 { get; set; }

    public bool? _102 { get; set; }

    public bool? _103 { get; set; }

    public bool? _11 { get; set; }

    public bool? _13 { get; set; }

    public bool? _15 { get; set; }

    public bool? _16 { get; set; }

    public bool? _161 { get; set; }

    public bool? _162 { get; set; }

    public bool? _1621 { get; set; }

    public bool? _163 { get; set; }

    public bool? _164 { get; set; }

    public bool? _165 { get; set; }

    public bool? _165a { get; set; }

    public bool? _166 { get; set; }

    public bool? _167 { get; set; }

    public bool? _167a { get; set; }

    public bool? _167b { get; set; }

    public bool? _18 { get; set; }

    public bool? _20 { get; set; }

    public bool? _21 { get; set; }

    public bool? _211 { get; set; }

    public bool? _22 { get; set; }

    public string? DqParaNumber { get; set; }

    public string? DqDiagnosis { get; set; }

    public string? AdditionalComments { get; set; }

    public string? Signature { get; set; }

    public bool? MedicalEvaluationFactSheet { get; set; }

    public string? ArtAndDsn { get; set; }

    public bool? Discharged { get; set; }

    public bool? Retired { get; set; }

    public bool? Cancer { get; set; }

    public bool? Coronary { get; set; }

    public bool? Dm { get; set; }

    public bool? Hiv { get; set; }

    public bool? Musculoskeletal { get; set; }

    public bool? Psych { get; set; }

    public bool? Pulmonary { get; set; }

    public bool? Rk { get; set; }

    public bool? Neuro { get; set; }

    public bool? Other { get; set; }

    public bool? Dental { get; set; }

    public bool? Gi { get; set; }

    public bool? Eent { get; set; }

    public string? HeSheNotCapped { get; set; }

    public DateTime? DateSentToFiche { get; set; }

    public bool? Renewal { get; set; }

    public bool? Archive { get; set; }

    public bool? ReActivate { get; set; }

    public string? InputBy { get; set; }

    public int? RcdId { get; set; }

    public string? RetiredDesc { get; set; }

    public string? DischargedDesc { get; set; }

    public bool? Imported { get; set; }
}
