// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class PhFieldType
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string? Placeholder { get; set; }

    public int DataTypeId { get; set; }

    public string? Datasource { get; set; }

    public string? Color { get; set; }

    public int? Length { get; set; }

    public virtual CoreLkupDataType DataType { get; set; } = null!;

    public virtual ICollection<PhFormField> PhFormFields { get; set; } = new List<PhFormField>();

    public virtual ICollection<PhFormValue> PhFormValues { get; set; } = new List<PhFormValue>();

    public virtual ICollection<RptPhUserQueryOutputField> RptPhUserQueryOutputFields { get; set; } = new List<RptPhUserQueryOutputField>();
}
