// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class PhFormValue
{
    public int RefId { get; set; }

    public int SectionId { get; set; }

    public int FieldId { get; set; }

    public int FieldTypeId { get; set; }

    public string Value { get; set; } = null!;

    public virtual PhField Field { get; set; } = null!;

    public virtual PhFieldType FieldType { get; set; } = null!;

    public virtual Form348Sc Ref { get; set; } = null!;

    public virtual PhSection Section { get; set; } = null!;
}
