// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class PkgLog
{
    public int Id { get; set; }

    public string? PkgName { get; set; }

    public DateTime? Starttime { get; set; }

    public DateTime? Endtime { get; set; }

    public int? NRowRawInserted { get; set; }

    public int? NRowInserted { get; set; }

    public int? NRowUpdated { get; set; }

    public int? NDeletedMembers { get; set; }

    public int? NModifiedRecords { get; set; }

    public string? SourceFileName { get; set; }
}
