// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class RecentlyUploadedDocument
{
    public int RefId { get; set; }

    public long DocGroupId { get; set; }

    public long? DocId { get; set; }

    public int? DocTypeId { get; set; }
}
