// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class ReminderEmail
{
    public int Id { get; set; }

    public int SettingId { get; set; }

    public string CaseId { get; set; } = null!;

    public DateOnly LastSentDate { get; set; }

    public DateOnly LastModifiedDate { get; set; }

    public int? SentCount { get; set; }

    public int MemberUnitId { get; set; }

    public virtual ReminderEmailSetting Setting { get; set; } = null!;
}
