// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class RptPhUserQuery
{
    public int Id { get; set; }

    public int UserQueryId { get; set; }

    public int ReportType { get; set; }

    public string? SortField { get; set; }

    public virtual ICollection<RptPhUserQueryClause> RptPhUserQueryClauses { get; set; } = new List<RptPhUserQueryClause>();

    public virtual ICollection<RptPhUserQueryOutputField> RptPhUserQueryOutputFields { get; set; } = new List<RptPhUserQueryOutputField>();

    public virtual RptUserQuery UserQuery { get; set; } = null!;
}
