// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class RptPhUserQueryClause
{
    public int Id { get; set; }

    public int PhqueryId { get; set; }

    public string WhereType { get; set; } = null!;

    public virtual RptPhUserQuery Phquery { get; set; } = null!;

    public virtual ICollection<RptPhUserQueryParam> RptPhUserQueryParams { get; set; } = new List<RptPhUserQueryParam>();
}
