// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class RptPhUserQueryParam
{
    public int Id { get; set; }

    public int PhclauseId { get; set; }

    public string WhereType { get; set; } = null!;

    public string OperatorType { get; set; } = null!;

    public string StartValue { get; set; } = null!;

    public string StartDisplay { get; set; } = null!;

    public string? EndValue { get; set; }

    public string? EndDisplay { get; set; }

    public int ExecuteOrder { get; set; }

    public virtual RptPhUserQueryClause Phclause { get; set; } = null!;
}
