// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class RptQueryField
{
    public int Id { get; set; }

    public string? FieldName { get; set; }

    public string? QueryType { get; set; }

    public int? SortOrder { get; set; }

    public string? TableName { get; set; }
}
