// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class RptUserQueryParam
{
    public int Id { get; set; }

    public int ClauseId { get; set; }

    public int SourceId { get; set; }

    public string OperatorType { get; set; } = null!;

    public string WhereType { get; set; } = null!;

    public string StartValue { get; set; } = null!;

    public string StartDisplay { get; set; } = null!;

    public string? EndValue { get; set; }

    public string? EndDisplay { get; set; }

    public int? ExecuteOrder { get; set; }

    public virtual RptUserQueryClause Clause { get; set; } = null!;

    public virtual RptQuerySource Source { get; set; } = null!;
}
