// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace AF.ECT.Data.Entities;

public partial class RptUserQuery
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Title { get; set; } = null!;

    public DateTime CreatedDate { get; set; }

    public DateTime ModifiedDate { get; set; }

    public bool Transient { get; set; }

    public string? OutputFields { get; set; }

    public string? SortFields { get; set; }

    public bool Shared { get; set; }

    public virtual ICollection<RptPhUserQuery> RptPhUserQueries { get; set; } = new List<RptPhUserQuery>();

    public virtual ICollection<RptUserQueryClause> RptUserQueryClauses { get; set; } = new List<RptUserQueryClause>();

    public virtual CoreUser User { get; set; } = null!;
}
