// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class SsisConfiguration
{
    public string ConfigurationFilter { get; set; } = null!;

    public string? ConfiguredValue { get; set; }

    public string PackagePath { get; set; } = null!;

    public string ConfiguredValueType { get; set; } = null!;
}
