// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Data.Entities;

public partial class TestCommandStruct
{
    public int CsId { get; set; }

    public string? Address1 { get; set; }

    public string? Address2 { get; set; }

    public string? BaseCode { get; set; }

    public string? City { get; set; }

    public string? CommandCode { get; set; }

    public string? CommandStructUtc { get; set; }

    public string? Component { get; set; }

    public string? Country { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CsIdParent { get; set; }

    public string? CsLevel { get; set; }

    public string? CsOperType { get; set; }

    public string? EMail { get; set; }

    public int? GainingCommandCsId { get; set; }

    public string? GeoLoc { get; set; }

    public string? LongName { get; set; }

    public string? MedicalService { get; set; }

    public string? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public DateTime? MrdssDocDate { get; set; }

    public string? MrdssDocId { get; set; }

    public string? MrdssDocReview { get; set; }

    public string? MrdssKind { get; set; }

    public string? PasCode { get; set; }

    public string? PhysExamYn { get; set; }

    public string? PostalCode { get; set; }

    public string? SchedulingYn { get; set; }

    public string? State { get; set; }

    public string? TimeZone { get; set; }

    public string? Uic { get; set; }

    public string? UnitDet { get; set; }

    public string? UnitKind { get; set; }

    public string? UnitNbr { get; set; }

    public string? UnitType { get; set; }

    public virtual CoreLkupUnitLevelType? CsLevelNavigation { get; set; }

    public virtual CoreLkupOperationType? CsOperTypeNavigation { get; set; }

    public virtual ICollection<TestCommandStructChain> TestCommandStructChains { get; set; } = new List<TestCommandStructChain>();

    public virtual CoreLkupTimeZone? TimeZoneNavigation { get; set; }
}
