// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AF.ECT.Data.Models;

/// <summary>
/// Entity Framework DbContext for the ALOD (Audit Log Operations Database) system.
/// </summary>
/// <remarks>
/// This context provides access to database entities and stored procedures for the
/// Radzen Blazor application. It is auto-generated by EF Core Power Tools and
/// should not be modified manually.
/// </remarks>
public partial class ALODContext : DbContext
{
    /// <summary>
    /// Initializes a new instance of the ALODContext.
    /// </summary>
    /// <param name="options">The options to be used by the DbContext.</param>
    /// <exception cref="ArgumentNullException">Thrown when options is null.</exception>
    public ALODContext(DbContextOptions<ALODContext> options)
        : base(options)
    {
    }

    /// <summary>
    /// Initializes a new instance of the ALODContext without options (for Audit.NET).
    /// </summary>
    public ALODContext()
    {
    }

    /// <summary>
    /// Configures the model for the context.
    /// </summary>
    /// <param name="modelBuilder">The builder being used to construct the model for this context.</param>
    /// <remarks>
    /// This method is called when the model for a derived context has been initialized,
    /// but before the model has been locked down and used to initialize the context.
    /// </remarks>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingPartial(modelBuilder);
    }

    /// <summary>
    /// Applies configurations for core entities that have been manually configured with detailed settings.
    /// </summary>
    /// <param name="modelBuilder">The builder being used to construct the model.</param>
    private void ApplyCoreEntityConfigurations(ModelBuilder modelBuilder)
    {
    }

    /// <summary>
    /// Applies configurations for all entities generated by the PowerShell script.
    /// These are template-based configurations that provide basic table mappings.
    /// </summary>
    /// <param name="modelBuilder">The builder being used to construct the model.</param>
    private void ApplyGeneratedEntityConfigurations(ModelBuilder modelBuilder)
    {
        // AFRC Oracle Data configurations
        
    }

    /// <summary>
    /// Allows configuration of the model that cannot be done automatically by the conventions.
    /// </summary>
    /// <param name="modelBuilder">The builder being used to construct the model for this context.</param>
    /// <remarks>
    /// This partial method can be implemented in another partial class to add
    /// custom model configuration that cannot be done through data annotations.
    /// </remarks>
    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
