// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
#pragma warning disable CS8604 // Possible null reference argument
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using AF.ECT.Server.Models.Interfaces;

namespace AF.ECT.Server.Models;

public partial class ALODContext
{
    private IALODContextProcedures? _procedures;

    /// <summary>
    /// Gets or sets the procedures interface for executing stored procedures.
    /// </summary>
    /// <value>The procedures interface instance.</value>
    public virtual IALODContextProcedures Procedures
    {
        get
        {
            if (_procedures is null) _procedures = new ALODContextProcedures(this);
            return _procedures;
        }
        set
        {
            _procedures = value;
        }
    }
}

