// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class ApplicationWarmupProcess
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public bool Active { get; set; }

    public virtual ICollection<ApplicationWarmupProcessLog> ApplicationWarmupProcessLogs { get; set; } = new List<ApplicationWarmupProcessLog>();
}
