// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class cmdStructChain_sp_GetChaninByUnitResult
    {
        public int cs_id { get; set; }
        [StringLength(107)]
        public string? unit { get; set; }
    }
}

