// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CommandStructHistory
{
    public int Id { get; set; }

    public int? PkgLogId { get; set; }

    public string Pascode { get; set; } = null!;

    public int CsId { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public string? Address1 { get; set; }

    public string? Address2 { get; set; }

    public string? BaseCode { get; set; }

    public string? City { get; set; }

    public string? CommandCode { get; set; }

    public string? CommandStructUtc { get; set; }

    public string? Component { get; set; }

    public string? Country { get; set; }

    public int? CsIdParent { get; set; }

    public string? CsLevel { get; set; }

    public string? CsOperType { get; set; }

    public string? GeoLoc { get; set; }

    public string? LongName { get; set; }

    public string? PostalCode { get; set; }

    public string? State { get; set; }

    public string? Uic { get; set; }

    public string? UnitDet { get; set; }

    public string? UnitKind { get; set; }

    public string? UnitNbr { get; set; }

    public string? UnitType { get; set; }

    public string? ChangeType { get; set; }

    public string? ParentPasCode { get; set; }
}
