// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CommandStructChainBackup
{
    public int CscId { get; set; }

    public int? CsId { get; set; }

    public string? ChainType { get; set; }

    public int? CscIdParent { get; set; }

    public string? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public byte? ViewType { get; set; }
}
