// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CommandStructTree
{
    public byte ViewType { get; set; }

    public string ParentPas { get; set; } = null!;

    public string ChildPas { get; set; } = null!;

    public int? ParentId { get; set; }

    public int? ChildId { get; set; }
}
