// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreLkupRule
{
    public byte Id { get; set; }

    public byte? WorkFlow { get; set; }

    public byte RuleType { get; set; }

    public string Name { get; set; } = null!;

    public string? Prompt { get; set; }

    public bool Active { get; set; }

    public virtual ICollection<CoreWorkStatusRule> CoreWorkStatusRules { get; set; } = new List<CoreWorkStatusRule>();

    public virtual CoreLkupRuleType RuleTypeNavigation { get; set; } = null!;

    public virtual CoreWorkflow? WorkFlowNavigation { get; set; }
}
