// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreLogChangeSet
{
    public int LogId { get; set; }

    public string Section { get; set; } = null!;

    public string Field { get; set; } = null!;

    public string Old { get; set; } = null!;

    public string New { get; set; } = null!;

    public virtual CoreLogAction Log { get; set; } = null!;
}
