// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreWitness
{
    public int Id { get; set; }

    public int LodId { get; set; }

    public byte WitnessType { get; set; }

    public byte OtherType { get; set; }

    public string Name { get; set; } = null!;

    public string? Address { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }
}
