// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CorePermissionRequest
{
    public int ReqId { get; set; }

    public int UserId { get; set; }

    public short PermId { get; set; }

    public DateTime DateReq { get; set; }

    public virtual CorePermission Perm { get; set; } = null!;

    public virtual CoreUser User { get; set; } = null!;
}
