// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreWorkflowDispositionMap
{
    public byte WorkflowId { get; set; }

    public int DispositionId { get; set; }

    public virtual CoreLkupDisposition Disposition { get; set; } = null!;

    public virtual CoreWorkflow Workflow { get; set; } = null!;
}
