// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class core_rule_sp_SelectOptionRuleResult
    {
        public int wsr_id { get; set; }
        public int wso_id { get; set; }
        public byte ruleId { get; set; }
        [StringLength(1000)]
        public string ruleData { get; set; } = default!;
        public bool? checkAll { get; set; }
    }
}

