// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreMemoLetterhead
{
    public byte Id { get; set; }

    public string Title { get; set; } = null!;

    public byte Version { get; set; }

    public string Compo { get; set; } = null!;

    public DateTime DateCreated { get; set; }

    public string LogoImageLeft { get; set; } = null!;

    public string HeaderTitle { get; set; } = null!;

    public int HeaderTitleSize { get; set; }

    public string HeaderSubtitle { get; set; } = null!;

    public int HeaderSubtitleSize { get; set; }

    public string Font { get; set; } = null!;

    public int FontSize { get; set; }

    public string HeaderFontColor { get; set; } = null!;

    public string LogoImageRight { get; set; } = null!;

    public string FooterImageCenter { get; set; } = null!;

    public DateTime EffectiveDate { get; set; }

    public virtual CoreLkupCompo CompoNavigation { get; set; } = null!;

    public virtual ICollection<CoreMemo> CoreMemos { get; set; } = new List<CoreMemo>();

    public virtual ICollection<CoreMemos2> CoreMemos2s { get; set; } = new List<CoreMemos2>();
}
