// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreWorkflow
{
    public byte WorkflowId { get; set; }

    public byte ModuleId { get; set; }

    public string Compo { get; set; } = null!;

    public string Title { get; set; } = null!;

    public bool Formal { get; set; }

    public bool Active { get; set; }

    public int? InitialStatus { get; set; }

    public virtual ICollection<CoreLkupRule> CoreLkupRules { get; set; } = new List<CoreLkupRule>();

    public virtual ICollection<CoreWorkStatusTracking> CoreWorkStatusTrackings { get; set; } = new List<CoreWorkStatusTracking>();

    public virtual ICollection<CoreWorkStatus> CoreWorkStatuses { get; set; } = new List<CoreWorkStatus>();

    public virtual ICollection<Form348Sarc> Form348Sarcs { get; set; } = new List<Form348Sarc>();

    public virtual ICollection<Form348Sc> Form348Scs { get; set; } = new List<Form348Sc>();

    public virtual ICollection<Form348> Form348s { get; set; } = new List<Form348>();

    public virtual CoreWorkStatus? InitialStatusNavigation { get; set; }

    public virtual CoreLkupModule Module { get; set; } = null!;

    public virtual ICollection<ReminderEmailSetting> ReminderEmailSettings { get; set; } = new List<ReminderEmailSetting>();
}
