// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreLkupRmu
{
    public int Id { get; set; }

    public string? Rmu { get; set; }

    public int? CsId { get; set; }

    public bool Collocated { get; set; }
}
