// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreAssociatedCase
{
    public byte WorkflowId { get; set; }

    public int RefId { get; set; }

    public byte AssociatedWorkflow { get; set; }

    public int AssociatedRefId { get; set; }

    public string? AssociatedCaseId { get; set; }
}
