// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class core_messages_sp_GetAllMessagesResult
    {
        public short messageId { get; set; }
        [StringLength(50)]
        public string? title { get; set; }
        public DateTime startTime { get; set; }
        public DateTime? endTime { get; set; }
        public bool popup { get; set; }
        public bool isAdminMessage { get; set; }
    }
}

