// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class core_pascodes_GetParentChainResult
    {
        public int cs_id { get; set; }
        [StringLength(100)]
        public string? ParentName { get; set; }
        [StringLength(4)]
        public string? parentPasCode { get; set; }
        public int? view_type { get; set; }
        public int Level { get; set; }
        public int? userUnit { get; set; }
    }
}

