// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class core_lookups_GetAllModulesResult
    {
        public byte moduleId { get; set; }
        [StringLength(50)]
        public string moduleName { get; set; } = default!;
        public bool isSpecialCase { get; set; }
    }
}

