// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreLkupFindingsText
{
    public int FindingId { get; set; }

    public int Workflow { get; set; }

    public int GroupId { get; set; }

    public string Description { get; set; } = null!;
}
