// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class core_ICD_sp_FindNatureOfIncidentValuesResult
    {
        public int Id { get; set; }
        [StringLength(50)]
        public string Value { get; set; } = default!;
        [StringLength(50)]
        public string Text { get; set; } = default!;
    }
}

