// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class core_workflowView_sp_GetAllWorkflowResult
    {
        public byte workflowId { get; set; }
        [StringLength(103)]
        public string title { get; set; } = default!;
    }
}

