// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreWorkStatus
{
    public int WsId { get; set; }

    public byte WorkflowId { get; set; }

    public int StatusId { get; set; }

    public byte SortOrder { get; set; }

    public bool IsBoardStatus { get; set; }

    public string? DisplayText { get; set; }

    public bool IsHolding { get; set; }

    public string? Compo { get; set; }

    public bool? IsConsult { get; set; }

    public virtual ICollection<CoreWorkStatusOption> CoreWorkStatusOptionWs { get; set; } = new List<CoreWorkStatusOption>();

    public virtual ICollection<CoreWorkStatusOption> CoreWorkStatusOptionWsIdOutNavigations { get; set; } = new List<CoreWorkStatusOption>();

    public virtual ICollection<CoreWorkStatusTracking> CoreWorkStatusTrackings { get; set; } = new List<CoreWorkStatusTracking>();

    public virtual ICollection<CoreWorkStatusValidation> CoreWorkStatusValidations { get; set; } = new List<CoreWorkStatusValidation>();

    public virtual ICollection<CoreWorkflow> CoreWorkflows { get; set; } = new List<CoreWorkflow>();

    public virtual ICollection<Form348Sarc> Form348Sarcs { get; set; } = new List<Form348Sarc>();

    public virtual ICollection<Form348Sc> Form348Scs { get; set; } = new List<Form348Sc>();

    public virtual ICollection<Form348> Form348s { get; set; } = new List<Form348>();

    public virtual ICollection<ReminderEmailSetting> ReminderEmailSettings { get; set; } = new List<ReminderEmailSetting>();

    public virtual CoreStatusCode Status { get; set; } = null!;

    public virtual CoreWorkflow Workflow { get; set; } = null!;
}
