// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreMessagesGroup
{
    public short MessageId { get; set; }

    public byte GroupId { get; set; }

    public virtual CoreUserGroup Group { get; set; } = null!;
}
