// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreLkupMemberCategory
{
    public int MemberStatusId { get; set; }

    public string MemberStatusDesc { get; set; } = null!;

    public int? SortOrder { get; set; }
}
