// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CorePageAccess
{
    public int MapId { get; set; }

    public int StatusId { get; set; }

    public byte GroupId { get; set; }

    public byte WorkflowId { get; set; }

    public byte Access { get; set; }

    public int PageId { get; set; }

    public virtual CoreUserGroup Group { get; set; } = null!;
}
