// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreLkUpFindingByReasonOf
{
    public int Id { get; set; }

    public string Description { get; set; } = null!;

    public virtual ICollection<Form348> Form348s { get; set; } = new List<Form348>();
}
