// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class core_KeyVal_sp_GetKeysUsingKeyTypeResult
    {
        public int KeyId { get; set; }
        [StringLength(200)]
        public string? KeyDescription { get; set; }
        public int KeyTypeId { get; set; }
        [StringLength(100)]
        public string KeyTypeName { get; set; } = default!;
    }
}

