// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreLkUpFinding
{
    public byte Id { get; set; }

    public string? FindingType { get; set; }

    public string? Description { get; set; }

    public virtual ICollection<Form261> Form261s { get; set; } = new List<Form261>();
}
