// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreUsersOnline
{
    public int UserId { get; set; }

    public int GroupId { get; set; }

    public DateTime LoginTime { get; set; }

    public DateTime LastAccess { get; set; }

    public string? SessionId { get; set; }

    public string? RemoteAddress { get; set; }
}
