// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreLkupNatureOfIncident
{
    public int Id { get; set; }

    public string Value { get; set; } = null!;

    public string Text { get; set; } = null!;

    public virtual ICollection<CoreLkupIcd9> Icds { get; set; } = new List<CoreLkupIcd9>();
}
