// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreLkupDawgrecommendation
{
    public byte Id { get; set; }

    public string Recommendation { get; set; } = null!;
}
