// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreLkupIcd9
{
    public int Icd9Id { get; set; }

    public string? Value { get; set; }

    public string? Text { get; set; }

    public int? ParentId { get; set; }

    public int? SortOrder { get; set; }

    public bool IsDisease { get; set; }

    public bool Active { get; set; }

    public bool? SeventhChr { get; set; }

    public int? DiagOrder { get; set; }

    public int? Icdversion { get; set; }

    public virtual ICollection<Form348Medical> Form348Medicals { get; set; } = new List<Form348Medical>();

    public virtual ICollection<Form348SarcIcd> Form348SarcIcds { get; set; } = new List<Form348SarcIcd>();

    public virtual ICollection<Form348Sc> Form348Scs { get; set; } = new List<Form348Sc>();

    public virtual ICollection<CoreLkupNatureOfIncident> Nois { get; set; } = new List<CoreLkupNatureOfIncident>();
}
