// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreLkupCancelReason
{
    public byte Id { get; set; }

    public string Description { get; set; } = null!;

    public byte DisplayOrder { get; set; }

    public virtual ICollection<Form348> Form348AppointingCancelReasons { get; set; } = new List<Form348>();

    public virtual ICollection<Form348> Form348ApprovingCancelReasons { get; set; } = new List<Form348>();
}
