// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreMemos2
{
    public int MemoId { get; set; }

    public int RefId { get; set; }

    public int ModuleId { get; set; }

    public byte TemplateId { get; set; }

    public bool Deleted { get; set; }

    public byte LetterHead { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<CoreMemoContents2> CoreMemoContents2s { get; set; } = new List<CoreMemoContents2>();

    public virtual CoreUser CreatedByNavigation { get; set; } = null!;

    public virtual CoreMemoLetterhead LetterHeadNavigation { get; set; } = null!;

    public virtual CoreMemoTemplate Template { get; set; } = null!;
}
