// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreMemoContents2
{
    public int Id { get; set; }

    public int MemoId { get; set; }

    public string Body { get; set; } = null!;

    public string? SigBlock { get; set; }

    public string? SuspenseDate { get; set; }

    public string? MemoDate { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public string? Attachments { get; set; }

    public virtual CoreUser CreatedByNavigation { get; set; } = null!;

    public virtual CoreMemos2 Memo { get; set; } = null!;
}
