// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class core_lookUps_sp_GetCancelReasonDescriptionByIdResult
    {
        [StringLength(150)]
        public string Description { get; set; } = default!;
    }
}

