// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreUserGroupsManagedBy
{
    public byte GroupId { get; set; }

    public byte ManagedBy { get; set; }

    public bool? Notify { get; set; }

    public bool? ViewBy { get; set; }

    public virtual CoreUserGroup Group { get; set; } = null!;

    public virtual CoreUserGroup ManagedByNavigation { get; set; } = null!;
}
