// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class core_lookUps_sp_InfoSourcesResult
    {
        [StringLength(100)]
        public string Description { get; set; } = default!;
        public int id { get; set; }
        public int sort_order { get; set; }
    }
}

