// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class core_memo_sp_GetKeyValuesResult
    {
        [StringLength(20)]
        public string? Value_Id { get; set; }
        [StringLength(50)]
        public string Value_Description { get; set; } = default!;
        [StringLength(2147483647)]
        public string? Value { get; set; }
    }
}

