// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreMemoTemplate
{
    public byte TemplateId { get; set; }

    public string Title { get; set; } = null!;

    public string Body { get; set; } = null!;

    public string? Attachments { get; set; }

    public bool Active { get; set; }

    public string? SigBlock { get; set; }

    public bool AddDate { get; set; }

    public bool AddSuspenseDate { get; set; }

    public string DataSource { get; set; } = null!;

    public string Compo { get; set; } = null!;

    public bool AddSignature { get; set; }

    public bool Phi { get; set; }

    public byte Module { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public int ModifiedBy { get; set; }

    public DateTime ModifiedDate { get; set; }

    public int? FontSize { get; set; }

    public virtual ICollection<CoreMemoGroup> CoreMemoGroups { get; set; } = new List<CoreMemoGroup>();

    public virtual ICollection<CoreMemo> CoreMemos { get; set; } = new List<CoreMemo>();

    public virtual ICollection<CoreMemos2> CoreMemos2s { get; set; } = new List<CoreMemos2>();

    public virtual CoreUser CreatedByNavigation { get; set; } = null!;

    public virtual CoreUser ModifiedByNavigation { get; set; } = null!;

    public virtual CoreLkupModule ModuleNavigation { get; set; } = null!;
}
