// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class core_pascode_sp_GetReportingResult
    {
        public int? cs_id { get; set; }
        [StringLength(20)]
        public string Chain_Type { get; set; } = default!;
        public int? parent_cs_Id { get; set; }
        [StringLength(100)]
        public string? parent_long_name { get; set; }
        [StringLength(100)]
        public string? Chain_Description { get; set; }
        [StringLength(4)]
        public string? parent_pas { get; set; }
    }
}

