// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreLkupScsubType
{
    public int SubTypeId { get; set; }

    public string SubTypeTitle { get; set; } = null!;

    public int AssociatedWorkflowId { get; set; }
}
