// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class core_lod_sp_GetAppealRequestsResult
    {
        public int appeal_id { get; set; }
        [StringLength(4)]
        public string? Protected_SSN { get; set; }
        [StringLength(100)]
        public string? Member_Name { get; set; }
        [StringLength(100)]
        public string Unit_Name { get; set; } = default!;
        [StringLength(50)]
        public string Case_Id { get; set; } = default!;
        [StringLength(50)]
        public string Status { get; set; } = default!;
        public string? Receive_Date { get; set; }
        public int? Days { get; set; }
    }
}

