// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreLkupPepprating
{
    public int RatingId { get; set; }

    public string RatingName { get; set; } = null!;

    public bool Active { get; set; }
}
