// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreLogPageGenerationTime
{
    public int GId { get; set; }

    public DateTime? ActionDate { get; set; }

    public string? MeasuredTime { get; set; }

    public string? CurrentPage { get; set; }

    public string? ReferringPage { get; set; }

    public string? Username { get; set; }

    public string? Role { get; set; }
}
