// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreWorkflowLock
{
    public int Id { get; set; }

    public int RefId { get; set; }

    public byte Module { get; set; }

    public int UserId { get; set; }

    public DateTime LockTime { get; set; }

    public virtual CoreLkupModule ModuleNavigation { get; set; } = null!;

    public virtual CoreUser User { get; set; } = null!;
}
