// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreLkupDbSignTemplate
{
    public byte TId { get; set; }

    public string? Title { get; set; }

    public string? TemplateTableName { get; set; }

    public string PrimaryKey { get; set; } = null!;

    public string? SecondaryKey { get; set; }
}
