// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreWorkStatusOption
{
    public int WsoId { get; set; }

    public int WsId { get; set; }

    public string DisplayText { get; set; } = null!;

    public bool Active { get; set; }

    public byte SortOrder { get; set; }

    public byte Template { get; set; }

    public int WsIdOut { get; set; }

    public int? Compo { get; set; }

    public virtual ICollection<CoreWorkStatusAction> CoreWorkStatusActions { get; set; } = new List<CoreWorkStatusAction>();

    public virtual ICollection<CoreWorkStatusRule> CoreWorkStatusRules { get; set; } = new List<CoreWorkStatusRule>();

    public virtual CoreWorkStatus Ws { get; set; } = null!;

    public virtual CoreWorkStatus WsIdOutNavigation { get; set; } = null!;
}
