// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreLkupDataType
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public virtual ICollection<PhFieldType> PhFieldTypes { get; set; } = new List<PhFieldType>();
}
