// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class CoreWorkStatusAction
{
    public int WsaId { get; set; }

    public int WsoId { get; set; }

    public byte ActionType { get; set; }

    public int Target { get; set; }

    public int? Data { get; set; }

    public virtual CoreLkupWorkflowAction ActionTypeNavigation { get; set; } = null!;

    public virtual CoreWorkStatusOption Wso { get; set; } = null!;
}
