// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class dev_sp_GetUnitsResult
    {
        public int id { get; set; }
        [StringLength(139)]
        public string? name { get; set; }
    }
}

