// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class DevLogin
{
    public int UserId { get; set; }

    public string Compo { get; set; } = null!;

    public int? RoleId { get; set; }
}
