// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class DocCategoryView
{
    public int DocCatViewId { get; set; }

    public int DocViewId { get; set; }

    public int DocCatId { get; set; }

    public int? ViewOrder { get; set; }

    public bool IsRedacted { get; set; }

    public virtual DocumentCategory2 DocCat { get; set; } = null!;

    public virtual DocumentView DocView { get; set; } = null!;
}
