// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class DocumentCategory2
{
    public int DocCatId { get; set; }

    public string CategoryDescription { get; set; } = null!;

    public virtual ICollection<DocCategoryView> DocCategoryViews { get; set; } = new List<DocCategoryView>();
}
