// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class Form348ScReassessment
{
    public int OriginalRefId { get; set; }

    public int ReassessmentRefId { get; set; }

    public virtual Form348Sc OriginalRef { get; set; } = null!;

    public virtual Form348Sc ReassessmentRef { get; set; } = null!;
}
