// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class Form348Unit
{
    public int Lodid { get; set; }

    public string? CmdrCircDetails { get; set; }

    public string? CmdrDutyDetermination { get; set; }

    public DateTime? CmdrDutyFrom { get; set; }

    public string? CmdrDutyOthers { get; set; }

    public DateTime? CmdrDutyTo { get; set; }

    public string? CmdrActivatedYn { get; set; }

    public DateTime ModifiedDate { get; set; }

    public int ModifiedBy { get; set; }

    public int? SourceInformation { get; set; }

    public string? Witnesses { get; set; }

    public string? SourceInformationSpecify { get; set; }

    public int? MemberOccurrence { get; set; }

    public DateTime? AbsentFrom { get; set; }

    public DateTime? AbsentTo { get; set; }

    public string? MemberOnOrders { get; set; }

    public string? MemberCredible { get; set; }

    public int? ProximateCause { get; set; }

    public string? ProximateCauseSpecify { get; set; }

    public int? Workflow { get; set; }

    public int? TravelOccurrence { get; set; }

    public bool? VerifiedStatus { get; set; }

    public bool? ProofOfStatus { get; set; }

    public bool? LOdinitiation { get; set; }

    public bool? WrittenDiagnosis { get; set; }

    public bool? MemberRequest { get; set; }

    public bool? PriorToDutytatus { get; set; }

    public string? StatusWorsened { get; set; }

    public bool? IncurredOrAggravated { get; set; }

    public string? StatusWhenInjuryed { get; set; }

    public string? StatusWhenInjuryedExplanation { get; set; }

    public string? OrdersAttached { get; set; }

    public string? Idtstatus { get; set; }

    public string? Utapsattached { get; set; }

    public bool? Pcarsattached { get; set; }

    public bool? Pcarshistory { get; set; }

    public bool? EightYearRule { get; set; }

    public virtual Form348 Lod { get; set; } = null!;
}
