// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class Form348PostProcessingAppeal
{
    public int AppealId { get; set; }

    public int InitialLodId { get; set; }

    public string? AppealStreet { get; set; }

    public string? AppealCity { get; set; }

    public string? AppealState { get; set; }

    public string? AppealZip { get; set; }

    public string? AppealCountry { get; set; }

    public DateOnly? MemberNotificationDate { get; set; }

    public string? HelpExtensionNumber { get; set; }

    public string? Email { get; set; }

    public virtual Form348 InitialLod { get; set; } = null!;
}
