// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class Form348Medical
{
    public int Lodid { get; set; }

    public string? MemberStatus { get; set; }

    public string? EventNatureType { get; set; }

    public string? EventNatureDetails { get; set; }

    public string? MedicalFacility { get; set; }

    public string? MedicalFacilityType { get; set; }

    public DateTime? TreatmentDate { get; set; }

    public string? DeathInvolvedYn { get; set; }

    public string? MvaInvolvedYn { get; set; }

    public int? Icd9Id { get; set; }

    public byte? EptsYn { get; set; }

    public string? PhysicianApprovalComments { get; set; }

    public int ModifiedBy { get; set; }

    public DateTime ModifiedDate { get; set; }

    public byte? PhysicianCancelReason { get; set; }

    public string? PhysicianCancelExplanation { get; set; }

    public string? DiagnosisText { get; set; }

    public string? Icd7thChar { get; set; }

    public int? MemberFrom { get; set; }

    public int? MemberComponent { get; set; }

    public int? MemberCategory { get; set; }

    public int? Influence { get; set; }

    public string? MemberResponsible { get; set; }

    public string? PsychEval { get; set; }

    public DateTime? PsychDate { get; set; }

    public string? RelevantCondition { get; set; }

    public string? OtherTest { get; set; }

    public DateTime? OtherTestDate { get; set; }

    public string? DeployedLocation { get; set; }

    public bool? ConditionEpts { get; set; }

    public bool? ServiceAggravated { get; set; }

    public string? MobilityStandards { get; set; }

    public string? MemberCondition { get; set; }

    public string? AlcoholTestDone { get; set; }

    public string? DrugTestDone { get; set; }

    public string? BoardFinalization { get; set; }

    public int? Workflow { get; set; }

    public bool? LOdinitiation { get; set; }

    public bool? WrittenDiagnosis { get; set; }

    public bool? MemberRequest { get; set; }

    public bool? PriorToDutytatus { get; set; }

    public string? StatusWorsened { get; set; }

    public virtual CoreLkupIcd9? Icd9 { get; set; }
}
