// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class Form348Sc
{
    public int ScId { get; set; }

    public byte ModuleId { get; set; }

    public int? AssociatedLod { get; set; }

    public string CaseId { get; set; } = null!;

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public int ModifiedBy { get; set; }

    public DateTime ModifiedDate { get; set; }

    public byte Workflow { get; set; }

    public int Status { get; set; }

    public byte? RwoaReason { get; set; }

    public string? RwoaExplantion { get; set; }

    public DateTime? RwoaDate { get; set; }

    public DateTime? SigDateMedTech { get; set; }

    public string? SigNameMedTech { get; set; }

    public string? SigTitleMedTech { get; set; }

    public DateTime? SigDateHqt { get; set; }

    public string? SigNameHqt { get; set; }

    public string? SigTitleHqt { get; set; }

    public DateTime? SigDateMedOff { get; set; }

    public string? SigNameMedOff { get; set; }

    public string? SigTitleMedOff { get; set; }

    public DateTime? SigDateHqtFinal { get; set; }

    public string? SigNameHqtFinal { get; set; }

    public string? SigTitleHqtFinal { get; set; }

    public int? MedTechApproved { get; set; }

    public int? HqtApproval1 { get; set; }

    public int? MedOffApproved { get; set; }

    public int? HqtApproval2 { get; set; }

    public string? MedTechApprovalComment { get; set; }

    public string? HqtApproval1Comment { get; set; }

    public string? MedOffApprovalComment { get; set; }

    public string? HqtApproval2Comment { get; set; }

    public string? ReturnComment { get; set; }

    public string MemberSsn { get; set; } = null!;

    public string MemberName { get; set; } = null!;

    public string MemberUnit { get; set; } = null!;

    public int? DocGroupId { get; set; }

    public DateTime? ApprovalDate { get; set; }

    public DateTime? ExpirationDate { get; set; }

    public int? InitialSc { get; set; }

    public int? AlcLetterType { get; set; }

    public int MemberCompo { get; set; }

    public int MemberUnitId { get; set; }

    public string? TmtNumber { get; set; }

    public DateTime? TmtReceiveDate { get; set; }

    public DateTime? SuspenseDate { get; set; }

    public DateTime? DateIn { get; set; }

    public DateTime? DateOut { get; set; }

    public string? CaseComments { get; set; }

    public int? MemberGrade { get; set; }

    public DateTime? MemberDob { get; set; }

    public string? PocUnit { get; set; }

    public string? PocPhoneDsn { get; set; }

    public string? PocEmail { get; set; }

    public int? IpebElection { get; set; }

    public DateTime? MuqRequestDate { get; set; }

    public DateTime? IpebSignatureDate { get; set; }

    public int? CoverLtrIncMemberStatement { get; set; }

    public int? CoverLtrIncContactAttemptDetails { get; set; }

    public DateTime? MedEvalFactSheetSignDate { get; set; }

    public DateTime? MedEvalFsWaiverSignDate { get; set; }

    public DateTime? Ps3811SignDate { get; set; }

    public DateTime? FirstClassMailDate { get; set; }

    public int? HqtechDisposition { get; set; }

    public DateTime? SigDatePoc { get; set; }

    public string? SigNamePoc { get; set; }

    public string? SigTitlePoc { get; set; }

    public int? PwaiverCategory { get; set; }

    public string? PwaiverCategoryText { get; set; }

    public int? PwaiverLength { get; set; }

    public int? FastTrackType { get; set; }

    public int? RequiresSpecialistForMgmt { get; set; }

    public int? MissedWorkDays { get; set; }

    public int? HadErUrgentCareVisits { get; set; }

    public string? HospitalizationList { get; set; }

    public int? RiskForSuddenIncapacitation { get; set; }

    public DateTime? SigDateDawg { get; set; }

    public string? SigNameDawg { get; set; }

    public string? SigTitleDawg { get; set; }

    public int? DawgRecommendation { get; set; }

    public int? YearsSatisfactoryService { get; set; }

    public string? FtDiagnosis { get; set; }

    public int? DxInterferesWithDuties { get; set; }

    public string? FtPrognosis { get; set; }

    public string? FtTreatment { get; set; }

    public string? FtMedicationsAndDosages { get; set; }

    public int? RecommendedFollowUpInterval { get; set; }

    public int? DaytimeSomnolence { get; set; }

    public string? DaySleepDescription { get; set; }

    public int? HasApneaEpisodes { get; set; }

    public string? ApneaEpisodeDescription { get; set; }

    public int? SleepStudyResults { get; set; }

    public decimal? BodyMassIndex { get; set; }

    public int? OralDevicesUsed { get; set; }

    public int? CpapRequired { get; set; }

    public int? BipapRequired { get; set; }

    public int? ResponseToDevices { get; set; }

    public decimal? FastingBloodSugar { get; set; }

    public decimal? HgbA1c { get; set; }

    public int? CurrentOptometryExam { get; set; }

    public int? HasSignificantConditions { get; set; }

    public string? OtherSignificantConditionsList { get; set; }

    public int? ControlledWithOralAgents { get; set; }

    public string? OralAgentsList { get; set; }

    public int? RequiresInsulin { get; set; }

    public string? InsulinDosageRegime { get; set; }

    public int? RequiresNonInsulinMed { get; set; }

    public int? PulmonaryFunctionTest { get; set; }

    public int? MethacholineChallenge { get; set; }

    public int? RequiresDailySteroids { get; set; }

    public int? RescueInhalerUsageFrequency { get; set; }

    public int? SymptomsExacerbatedByColdOrExercise { get; set; }

    public string? ExerciseOrColdExacerbatedSymptomDescription { get; set; }

    public int? NormalPftWithTreatment { get; set; }

    public int? HoIntubation { get; set; }

    public decimal? DailySteroidsDosage { get; set; }

    public string? Dafsc { get; set; }

    public int? DafscIsSuitable { get; set; }

    public string? ErUrgentCareVisitDetails { get; set; }

    public int? HadHospitalizations { get; set; }

    public string? RmuInitials { get; set; }

    public int? IpebRefusal { get; set; }

    public int? WwdDocsAttached { get; set; }

    public int? CoverLetterUploaded { get; set; }

    public int? AfForm469Uploaded { get; set; }

    public DateTime? MuqUploadDate { get; set; }

    public int? UnitCmdrMemoUploaded { get; set; }

    public int? PrivatePhysicianDocsUploaded { get; set; }

    public DateTime? Ps3811RequestDate { get; set; }

    public int? Ps3811Uploaded { get; set; }

    public int? MemberLetterUploaded { get; set; }

    public int? NarrativeSummaryUploaded { get; set; }

    public int? MuqValid { get; set; }

    public int? ExacerbatedSymptomsReqOralSteroids { get; set; }

    public string? ExacerbatedSymptomsOralSteroidsDosage { get; set; }

    public int? Icd9Id { get; set; }

    public string? Icd9Description { get; set; }

    public DateTime? ReturnToDutyDate { get; set; }

    public int? MedGroupName { get; set; }

    public int? RmuName { get; set; }

    public int? MemberStatusId { get; set; }

    public int? HasAdminLod { get; set; }

    public string? DqParagraph { get; set; }

    public DateTime? DqCompletionDate { get; set; }

    public int? CaseCancelReason { get; set; }

    public string? CaseCancelExplanation { get; set; }

    public DateTime? SafLetterUploadDate { get; set; }

    public int? ApprovingAuthorityType { get; set; }

    public DateTime? ForwardDate { get; set; }

    public DateTime? NotificationDate { get; set; }

    public DateTime? CaseCancelDate { get; set; }

    public int? ReturnToGroup { get; set; }

    public int? ReturnByGroup { get; set; }

    public int? MedOffConcur { get; set; }

    public string? MemberAddressStreet { get; set; }

    public string? MemberAddressCity { get; set; }

    public string? MemberAddressState { get; set; }

    public string? MemberAddressZip { get; set; }

    public string? MemberHomePhone { get; set; }

    public int? MemberTricareRegion { get; set; }

    public string? FollowUpCare { get; set; }

    public string? MedicalProvider { get; set; }

    public string? MtfSuggested { get; set; }

    public string? MilitaryTreatmentFacilityInitial { get; set; }

    public DateTime? MtfInitialTreatmentDate { get; set; }

    public int? MtfSuggestedDistance { get; set; }

    public int? MtfSuggestedChoice { get; set; }

    public string? UnitPocName { get; set; }

    public int? UnitPocRank { get; set; }

    public string? UnitPocTitle { get; set; }

    public string? UnitPocPhone { get; set; }

    public string? MedicalProfileInfo { get; set; }

    public DateTime? InjuryIllnessDate { get; set; }

    public string? DeciExpl { get; set; }

    public DateTime? HighTenureDate { get; set; }

    public int? MemoTemplateId { get; set; }

    public int? Majcom { get; set; }

    public int? SimDeployment { get; set; }

    public DateTime? DeployStartDate { get; set; }

    public DateTime? DeployEndDate { get; set; }

    public string? DeployLocation { get; set; }

    public string? LineNumber { get; set; }

    public string? LineRemarks { get; set; }

    public DateTime? Code37InitDate { get; set; }

    public DateTime? SurgeryDate { get; set; }

    public int? AssociatedSc { get; set; }

    public int? CaseType { get; set; }

    public string? Justification { get; set; }

    public int? PeppType { get; set; }

    public int? Rating { get; set; }

    public int? Renewal { get; set; }

    public int? BaseAssign { get; set; }

    public int? CompletedByUnit { get; set; }

    public string? TypeName { get; set; }

    public string? RatingName { get; set; }

    public DateTime? DateReceived { get; set; }

    public int SubWorkflowType { get; set; }

    public string? Icd7thChar { get; set; }

    public bool? WaiverRequired { get; set; }

    public DateTime? WaiverExpirationDate { get; set; }

    public DateTime? CertificationDate { get; set; }

    public int? SubCaseType { get; set; }

    public int? CertificationStamp { get; set; }

    public string? FreeText { get; set; }

    public string? CompletedByUnitName { get; set; }

    public string? CaseTypeName { get; set; }

    public string? SubCaseTypeName { get; set; }

    public long? StampedDocId { get; set; }

    public int? MedOffPrevDisposition { get; set; }

    public int? AltAlcLetterType { get; set; }

    public DateTime? SigDateUnitPh { get; set; }

    public string? SigNameUnitPh { get; set; }

    public string? SigTitleUnitPh { get; set; }

    public DateTime? SigDateHqDph { get; set; }

    public string? SigNameHqDph { get; set; }

    public string? SigTitleHqDph { get; set; }

    public int? PhWingRmuId { get; set; }

    public int? PhUserId { get; set; }

    public bool? IsDelinquent { get; set; }

    public DateTime? PhReportingPeriod { get; set; }

    public DateTime? PhLastModified { get; set; }

    public int? SecondaryCertificationStamp { get; set; }

    public string? SecondaryFreeText { get; set; }

    public int? Process { get; set; }

    public DateTime? RenewalDate { get; set; }

    public int? HasAdminSc { get; set; }

    public string? SeniorMedicalReviewerConcur { get; set; }

    public int? SeniorMedicalReviewerApproved { get; set; }

    public string? SeniorMedicalReviewerComment { get; set; }

    public int? AlternateAlcLetterType { get; set; }

    public int? AlternateAltAlcLetterType { get; set; }

    public DateTime? AlternateApprovalDate { get; set; }

    public DateTime? AlternateCertificationDate { get; set; }

    public DateTime? AlternateDqCompletionDate { get; set; }

    public string? AlternateDqParagraph { get; set; }

    public DateTime? AlternateExpirationDate { get; set; }

    public int? AlternateMedOffConcur { get; set; }

    public int? AlternateMemoTemplateId { get; set; }

    public int? AlternateProcess { get; set; }

    public int? AlternatePwaiverLength { get; set; }

    public DateTime? AlternateReturnToDutyDate { get; set; }

    public DateTime? PhaDate { get; set; }

    public int? InitialTour { get; set; }

    public int? FollowOnTour { get; set; }

    public string? PocRankAndName { get; set; }

    public string? MilitaryTreatmentFacilityCityStateZip { get; set; }

    public string? MemberStatus { get; set; }

    public string? MemberCategory { get; set; }

    public bool? IawAfi { get; set; }

    public string? AccidentOrHistoryDetails { get; set; }

    public virtual Form348? AssociatedLodNavigation { get; set; }

    public virtual CoreUser CreatedByNavigation { get; set; } = null!;

    public virtual ICollection<Form348PscdFinding> Form348PscdFindings { get; set; } = new List<Form348PscdFinding>();

    public virtual CoreLkupIcd9? Icd9 { get; set; }

    public virtual Form348Sc? InitialScNavigation { get; set; }

    public virtual ICollection<Form348Sc> InverseInitialScNavigation { get; set; } = new List<Form348Sc>();

    public virtual CoreUser ModifiedByNavigation { get; set; } = null!;

    public virtual CoreLkupModule Module { get; set; } = null!;

    public virtual ICollection<PhFormValue> PhFormValues { get; set; } = new List<PhFormValue>();

    public virtual CoreLkupRwoareason? RwoaReasonNavigation { get; set; }

    public virtual CoreWorkStatus StatusNavigation { get; set; } = null!;

    public virtual CoreWorkflow WorkflowNavigation { get; set; } = null!;
}
