// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class Form348
{
    public int LodId { get; set; }

    public string CaseId { get; set; } = null!;

    public int Status { get; set; }

    public byte Workflow { get; set; }

    public string MemberName { get; set; } = null!;

    public string MemberSsn { get; set; } = null!;

    public int MemberGrade { get; set; }

    public string MemberUnit { get; set; } = null!;

    public int MemberUnitId { get; set; }

    public DateTime? MemberDob { get; set; }

    public string MemberCompo { get; set; } = null!;

    public int CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public int ModifiedBy { get; set; }

    public DateTime ModifiedDate { get; set; }

    public int? DocGroupId { get; set; }

    public bool FormalInv { get; set; }

    public string? MedTechComments { get; set; }

    public int? AppAuthUserId { get; set; }

    public bool Deleted { get; set; }

    public byte? RwoaReason { get; set; }

    public string? RwoaExplantion { get; set; }

    public DateTime? RwoaDate { get; set; }

    public string? FinalDecision { get; set; }

    public string? BoardForGeneralYn { get; set; }

    public DateTime? SigDateUnitCommander { get; set; }

    public string? SigNameUnitCommander { get; set; }

    public DateTime? SigDateMedOfficer { get; set; }

    public string? SigNameMedOfficer { get; set; }

    public DateTime? SigDateLegal { get; set; }

    public string? SigNameLegal { get; set; }

    public DateTime? SigDateAppointing { get; set; }

    public string? SigNameAppointing { get; set; }

    public DateTime? SigDateBoardLegal { get; set; }

    public string? SigNameBoardLegal { get; set; }

    public DateTime? SigDateBoardMedical { get; set; }

    public string? SigNameBoardMedical { get; set; }

    public DateTime? SigDateBoardAdmin { get; set; }

    public string? SigNameBoardAdmin { get; set; }

    public DateTime? SigDateApproval { get; set; }

    public string? SigNameApproval { get; set; }

    public string? SigTitleApproval { get; set; }

    public DateTime? SigDateFormalApproval { get; set; }

    public string? SigNameFormalApproval { get; set; }

    public string? SigTitleFormalApproval { get; set; }

    public string? ToUnit { get; set; }

    public string? FromUnit { get; set; }

    public byte? FinalFindings { get; set; }

    public DateTime? IoCompletionDate { get; set; }

    public string? IoInstructions { get; set; }

    public string? IoPocInfo { get; set; }

    public bool Sarc { get; set; }

    public bool Restricted { get; set; }

    public string? IoSsn { get; set; }

    public int? IoUid { get; set; }

    public short AaPtype { get; set; }

    public string? ReturnComment { get; set; }

    public bool? MemberNotified { get; set; }

    public int? CompletedByUnit { get; set; }

    public string? SigTitleBoardAdmin { get; set; }

    public string? SigTitleBoardMedical { get; set; }

    public string? SigTitleBoardLegal { get; set; }

    public string? SigTitleAppointing { get; set; }

    public string? SigTitleLegal { get; set; }

    public string? SigTitleUnitCommander { get; set; }

    public string? SigTitleMedOfficer { get; set; }

    public int? ParentId { get; set; }

    public bool? IsAttachPas { get; set; }

    public int? MemberAttachedUnitId { get; set; }

    public int? ReturnToGroup { get; set; }

    public int? ReturnByGroup { get; set; }

    public string? BoardTechComments { get; set; }

    public string? SigNameMpf { get; set; }

    public DateTime? SigDateMpf { get; set; }

    public string? SigTitleMpf { get; set; }

    public bool? IsFormalCancelRecommended { get; set; }

    public byte? AppointingCancelReasonId { get; set; }

    public string? AppointingCancelExplanation { get; set; }

    public byte? ApprovingCancelReasonId { get; set; }

    public string? ApprovingCancelExplanation { get; set; }

    public string? SigNameLodPm { get; set; }

    public DateTime? SigDateLodPm { get; set; }

    public string? SigTitleLodPm { get; set; }

    public string? SigNameBoardA1 { get; set; }

    public DateTime? SigDateBoardA1 { get; set; }

    public string? SigTitleBoardA1 { get; set; }

    public bool? HasCredibleService { get; set; }

    public bool? WasMemberOnOrders { get; set; }

    public int? ApprovingAuthorityUserId { get; set; }

    public int? Tmn { get; set; }

    public int? Tms { get; set; }

    public string? AppointingUnit { get; set; }

    public DateTime? SigDateFormalLegal { get; set; }

    public string? SigNameFormalLegal { get; set; }

    public string? SigTitleFormalLegal { get; set; }

    public DateTime? SigDateFormalAppointing { get; set; }

    public string? SigNameFormalAppointing { get; set; }

    public string? SigTitleFormalAppointing { get; set; }

    public DateTime? SigDateFormalBoardMedical { get; set; }

    public string? SigNameFormalBoardMedical { get; set; }

    public string? SigTitleFormalBoardMedical { get; set; }

    public DateTime? SigDateFormalBoardLegal { get; set; }

    public string? SigNameFormalBoardLegal { get; set; }

    public string? SigTitleFormalBoardLegal { get; set; }

    public DateTime? SigDateFormalBoardAdmin { get; set; }

    public string? SigNameFormalBoardAdmin { get; set; }

    public string? SigTitleFormalBoardAdmin { get; set; }

    public DateTime? SigDateFormalBoardA1 { get; set; }

    public string? SigNameFormalBoardA1 { get; set; }

    public string? SigTitleFormalBoardA1 { get; set; }

    public bool? RwoaDirectReply { get; set; }

    public int? WingccNilodByreasonof { get; set; }

    public bool IsPostProcessingComplete { get; set; }

    public string? LodPm { get; set; }

    public virtual CoreLkupPersonnelType AaPtypeNavigation { get; set; } = null!;

    public virtual CoreUser? AppAuthUser { get; set; }

    public virtual CoreLkupCancelReason? AppointingCancelReason { get; set; }

    public virtual CoreLkupCancelReason? ApprovingCancelReason { get; set; }

    public virtual CoreUser CreatedByNavigation { get; set; } = null!;

    public virtual ICollection<Form348Finding> Form348Findings { get; set; } = new List<Form348Finding>();

    public virtual Form348PostProcessing? Form348PostProcessing { get; set; }

    public virtual ICollection<Form348PostProcessingAppeal> Form348PostProcessingAppeals { get; set; } = new List<Form348PostProcessingAppeal>();

    public virtual ICollection<Form348Sc> Form348Scs { get; set; } = new List<Form348Sc>();

    public virtual Form348Unit? Form348Unit { get; set; }

    public virtual CoreLkupGrade MemberGradeNavigation { get; set; } = null!;

    public virtual CoreUser ModifiedByNavigation { get; set; } = null!;

    public virtual CoreLkupRwoareason? RwoaReasonNavigation { get; set; }

    public virtual CoreWorkStatus StatusNavigation { get; set; } = null!;

    public virtual CoreLkUpFindingByReasonOf? WingccNilodByreasonofNavigation { get; set; }

    public virtual CoreWorkflow WorkflowNavigation { get; set; } = null!;
}
