// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class Form348IncapExt
{
    public int ExtId { get; set; }

    public int ScId { get; set; }

    public short? ExtNumber { get; set; }

    public DateTime? ExtStartDate { get; set; }

    public DateTime? ExtEndDate { get; set; }

    public bool? MedExtRecommendation { get; set; }

    public bool? ICExtRecommendation { get; set; }

    public bool? WJaConcurWithIc { get; set; }

    public bool? FinIncomeLost { get; set; }

    public bool? WccExtApproval { get; set; }

    public bool? OprExtApproval { get; set; }

    public bool? OcrExtApproval { get; set; }

    public bool? DosExtApproval { get; set; }

    public bool? CcrExtApproval { get; set; }

    public bool? VcrExtApproval { get; set; }

    public bool? DopExtApproval { get; set; }

    public bool? CafrExtApproval { get; set; }

    public DateTime? MedAmrostartDate { get; set; }

    public DateTime? MedAmroendDate { get; set; }

    public string? MedAmrodisposition { get; set; }

    public DateTime? MedNextAmrostartDate { get; set; }

    public DateTime? MedNextAmroendDate { get; set; }

    public string? MedIrilostatus { get; set; }

    public virtual Form348IncapFinding Sc { get; set; } = null!;
}
