// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class Form348_sp_GetIolistResult
    {
        [StringLength(100)]
        public string? Value { get; set; }
        [StringLength(111)]
        public string? Name { get; set; }
    }
}

