// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class Form348SarcIcd
{
    public int Id { get; set; }

    public int Sarcid { get; set; }

    public int IcdcodeId { get; set; }

    public string? Icd7thChar { get; set; }

    public virtual CoreLkupIcd9 Icdcode { get; set; } = null!;

    public virtual Form348Sarc Sarc { get; set; } = null!;
}
