// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class Form348ScPeppType
{
    public int RefId { get; set; }

    public int TypeId { get; set; }

    public virtual Form348Sc Ref { get; set; } = null!;

    public virtual CoreLkupPepptype Type { get; set; } = null!;
}
