// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class GetCompletedECTCases_dailyResult
    {
        [Column("Start Date")]
        public DateTime? StartDate { get; set; }
        [Column("End Date")]
        public DateTime? EndDate { get; set; }
    }
}

