// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class GetOpenCases_ECTResult
    {
        [Column("Report Start Date")]
        [StringLength(20)]
        public string? ReportStartDate { get; set; }
        [Column("Report End Date")]
        [StringLength(20)]
        public string? ReportEndDate { get; set; }
    }
}

