// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class GetSignedECTCasesByUserGroupResult
    {
        [StringLength(50)]
        public string? caseId { get; set; }
        [Column("Case Type")]
        [StringLength(50)]
        public string CaseType { get; set; } = default!;
        [Column("Date Signed")]
        public DateTime DateSigned { get; set; }
        [StringLength(100)]
        public string LastName { get; set; } = default!;
        [StringLength(100)]
        public string FirstName { get; set; } = default!;
        [StringLength(100)]
        public string name { get; set; } = default!;
        [StringLength(50)]
        public string actionName { get; set; } = default!;
    }
}

