// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class GradeAbbreviation
{
    public int AbbreviationTypeId { get; set; }

    public int GradeCode { get; set; }

    public string Abbreviation { get; set; } = null!;

    public virtual CoreLkupGradeAbbreviationType AbbreviationType { get; set; } = null!;

    public virtual CoreLkupGrade GradeCodeNavigation { get; set; } = null!;
}
