// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class HyperLinkType
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public virtual ICollection<HyperLink> HyperLinks { get; set; } = new List<HyperLink>();
}
