// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class ImpLodActiveDuty
{
    public string? AdId { get; set; }

    public string? Ssn { get; set; }

    public string? FirstName { get; set; }

    public string? MiddleInitial { get; set; }

    public string? LastName { get; set; }

    public string? Rank { get; set; }

    public string? DutyTitle { get; set; }

    public string? Afsc { get; set; }

    public string? Email { get; set; }

    public string? Telephone { get; set; }

    public string? Unit { get; set; }

    public string? UnitAddress { get; set; }

    public string? ExpirationDate { get; set; }

    public string? CreatedDate { get; set; }

    public string? CreatedBy { get; set; }

    public string? ModifiedDate { get; set; }

    public string? ModifiedBy { get; set; }
}
