// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class ImportErrorLog
{
    public string? UpdatingData { get; set; }

    public string? StoredProc { get; set; }

    public string? Message { get; set; }

    public int? Rcphalodid { get; set; }

    public DateTime? Time { get; set; }

    public string? ErrorMessage { get; set; }
}
