// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class ImpProcessValidStatus
{
    public string? PvsId { get; set; }

    public string? ProcId { get; set; }

    public string? ProcessName { get; set; }

    public string? ProcStatus { get; set; }

    public string? StatusSeq { get; set; }

    public string? StatusMeaning { get; set; }

    public string? RequiredYn { get; set; }

    public string? ClosesProcessYn { get; set; }

    public string? ResponsibilityLevel { get; set; }

    public string? CreatedBy { get; set; }

    public string? CreatedDate { get; set; }

    public string? ModifiedBy { get; set; }

    public string? ModifiedDate { get; set; }
}
