// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class MemberDataChangeHistory
{
    public string Ssan { get; set; } = null!;

    public string? FirstName { get; set; }

    public string? MiddleNames { get; set; }

    public string? LastName { get; set; }

    public string? Suffix { get; set; }

    public string? PasGaining { get; set; }

    public DateTime? AsgReptNltDate { get; set; }

    public string? RcdId { get; set; }

    public string? RecStatCurr { get; set; }

    public string? Pas { get; set; }

    public string? CommDutyPhone { get; set; }

    public string? OfficeSymbol { get; set; }

    public string? LocalAddrStreet { get; set; }

    public string? LocalAddrCity { get; set; }

    public string? LocalAddrState { get; set; }

    public string? HomePhone { get; set; }

    public string? AdrsMailDomCity { get; set; }

    public string? AdrsMailDomState { get; set; }

    public string? AdrsMailZip { get; set; }

    public int? GrCurr { get; set; }

    public string? DyPosnNr { get; set; }

    public string? Dafsc { get; set; }

    public string? DutyStatus { get; set; }

    public DateTime? DutyStatusEffDate { get; set; }

    public DateTime? DutyStatusExpDate { get; set; }

    public string? DeplAvailStatusAdmin { get; set; }

    public DateTime? DeplAvailStatusAExD { get; set; }

    public string? DeplAvailStatusPhys { get; set; }

    public DateTime? DeplAvailStatusPExD { get; set; }

    public string? DeplAvailStatusLegal { get; set; }

    public DateTime? DeplAvailStatusLExD { get; set; }

    public string? DeplAvailStatusTime { get; set; }

    public DateTime? DeplAvailStatusTExD { get; set; }

    public string? Pafsc { get; set; }

    public string? Afsc2 { get; set; }

    public string? Afsc3 { get; set; }

    public string? SexSvcMbr { get; set; }

    public DateTime? Dob { get; set; }

    public DateTime? RetSepEffDateProj { get; set; }

    public DateTime? Dos { get; set; }

    public string? SvcComp { get; set; }

    public DateTime? Tafcsd { get; set; }

    public DateTime? Tafmsd { get; set; }

    public DateTime? Ets { get; set; }

    public string? PasNumber { get; set; }

    public string? Zip { get; set; }

    public string ChangeType { get; set; } = null!;

    public DateTime Date { get; set; }

    public string? AttachPas { get; set; }
}
