// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class OverrideCase_GetAvailableStatusesRRResult
    {
        [StringLength(50)]
        public string? CaseNumber { get; set; }
        public int UpdateToId { get; set; }
        [StringLength(50)]
        public string NewStatusDesc { get; set; } = default!;
    }
}

