// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class PaldocumentLookup
{
    public int PalDocId { get; set; }

    public string Url { get; set; } = null!;

    public string LastName { get; set; } = null!;

    public string Last4Ssn { get; set; } = null!;

    public int DocYear { get; set; }

    public int DocMonth { get; set; }
}
