// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class PH_FormField_sp_GetByIdsResult
    {
        public int SectionId { get; set; }
        public int FieldId { get; set; }
        public int FieldTypeId { get; set; }
        public int FieldDisplayOrder { get; set; }
        public int FieldTypeDisplayOrder { get; set; }
        [StringLength(100)]
        public string? ToolTip { get; set; }
    }
}

