// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class PH_FieldType_sp_GetAllResult
    {
        public int Id { get; set; }
        [StringLength(100)]
        public string Name { get; set; } = default!;
        public int DataTypeId { get; set; }
        [StringLength(200)]
        public string? Datasource { get; set; }
        [StringLength(25)]
        public string? Placeholder { get; set; }
        [StringLength(50)]
        public string? Color { get; set; }
        public int? Length { get; set; }
    }
}

