// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class PhFormField
{
    public int SectionId { get; set; }

    public int FieldId { get; set; }

    public int FieldTypeId { get; set; }

    public int FieldDisplayOrder { get; set; }

    public int FieldTypeDisplayOrder { get; set; }

    public string? ToolTip { get; set; }

    public virtual PhField Field { get; set; } = null!;

    public virtual PhFieldType FieldType { get; set; } = null!;

    public virtual PhSection Section { get; set; } = null!;
}
