// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class PhSection
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public int? ParentId { get; set; }

    public int FieldColumns { get; set; }

    public bool IsTopLevel { get; set; }

    public int DisplayOrder { get; set; }

    public bool PageBreak { get; set; }

    public virtual ICollection<PhFormField> PhFormFields { get; set; } = new List<PhFormField>();

    public virtual ICollection<PhFormValue> PhFormValues { get; set; } = new List<PhFormValue>();

    public virtual ICollection<RptPhUserQueryOutputField> RptPhUserQueryOutputFields { get; set; } = new List<RptPhUserQueryOutputField>();
}
