// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class PreviousWeeksEctcase
{
    public byte WorkFlowId { get; set; }

    public string MemberName { get; set; } = null!;

    public string CaseId { get; set; } = null!;

    public string MemberUnit { get; set; } = null!;

    public string Description { get; set; } = null!;

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string ReportStart { get; set; } = null!;

    public string ReportEnd { get; set; } = null!;
}
