// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class PriorityUnitsNov19
{
    public decimal? Id { get; set; }

    public string? Pas { get; set; }

    public decimal? Priority { get; set; }
}
