// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class ReminderEmailGetListResult
    {
        public int id { get; set; }
        [StringLength(50)]
        public string caseId { get; set; } = default!;
        [StringLength(200)]
        public string? email { get; set; }
        public int? daysPending { get; set; }
        [StringLength(50)]
        public string moduleName { get; set; } = default!;
        public int templateId { get; set; }
    }
}

