// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class ReminderGetInactiveSettingsResult
    {
        public int i_id { get; set; }
        public int interval { get; set; }
        public int notification_interval { get; set; }
        public int templateId { get; set; }
        public bool? active { get; set; }
    }
}

