// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class report_sp_LODComplianceAccuracyResult
    {
        public int? UnitId { get; set; }
        [StringLength(100)]
        public string? MemberUnit { get; set; }
        public int? Accuracy { get; set; }
    }
}

