// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class report_RowaCountResult
    {
        public byte ID { get; set; }
        [StringLength(150)]
        public string Description { get; set; } = default!;
        public int? TotalCount { get; set; }
    }
}

