// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class report_sp_DetailStatisticsResult
    {
        public int lodid { get; set; }
        [StringLength(50)]
        public string case_id { get; set; } = default!;
        [StringLength(100)]
        public string member_name { get; set; } = default!;
        [StringLength(100)]
        public string member_unit { get; set; } = default!;
        public DateTime created_date { get; set; }
        public string? ReceiveDate { get; set; }
    }
}

