// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class ReportStoredResult
{
    public int UserId { get; set; }

    public string ReportTitle { get; set; } = null!;

    public string ResultData { get; set; } = null!;
}
