// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class report_sp_GetParticipationWaiversResult
    {
        public int RefId { get; set; }
        [StringLength(50)]
        public string CaseId { get; set; } = default!;
        [StringLength(100)]
        public string Name { get; set; } = default!;
        [StringLength(4)]
        public string? SSN { get; set; }
        public int Compo { get; set; }
        [StringLength(4)]
        public string? Pascode { get; set; }
        [StringLength(100)]
        public string? UnitName { get; set; }
        public string? ApprovalDate { get; set; }
        public int? DaysRemaining { get; set; }
        public int? DaysUsed { get; set; }
        public int? MemberWaivers { get; set; }
    }
}

