// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class report_pkgLogResult
    {
        public DateTime? starttime { get; set; }
        public DateTime? endtime { get; set; }
        [StringLength(50)]
        public string? pkgName { get; set; }
        public int? nRowRawInserted { get; set; }
        public int? nRowInserted { get; set; }
        public int? nRowUpdated { get; set; }
        public int? nModifiedRecords { get; set; }
        public int? nDeletedMembers { get; set; }
    }
}

