// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class Return
{
    public int ReturnId { get; set; }

    public int RefId { get; set; }

    public int WorkstatusTo { get; set; }

    public int WorkstatusFrom { get; set; }

    public byte Workflow { get; set; }

    public int? SentTo { get; set; }

    public byte? ReasonSentBack { get; set; }

    public string? ExplanationForSendingBack { get; set; }

    public int? Sender { get; set; }

    public DateTime? DateSent { get; set; }

    public string? CommentsBackToSender { get; set; }

    public DateTime? DateSentBack { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public bool? Rerouting { get; set; }

    public bool BoardReturn { get; set; }
}
