// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class RptPhUserQueryOutputField
{
    public int Id { get; set; }

    public int PhqueryId { get; set; }

    public int SectionId { get; set; }

    public int FieldId { get; set; }

    public int FieldTypeId { get; set; }

    public virtual PhField Field { get; set; } = null!;

    public virtual PhFieldType FieldType { get; set; } = null!;

    public virtual RptPhUserQuery Phquery { get; set; } = null!;

    public virtual PhSection Section { get; set; } = null!;
}
