// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class RptQuerySource
{
    public int Id { get; set; }

    public string DisplayName { get; set; } = null!;

    public string FieldName { get; set; } = null!;

    public string TableName { get; set; } = null!;

    public string DataType { get; set; } = null!;

    public string? LookupSource { get; set; }

    public string? LookupValue { get; set; }

    public string? LookupText { get; set; }

    public string? LookupSort { get; set; }

    public string? LookupWhere { get; set; }

    public string? LookupWhereValue { get; set; }

    public virtual ICollection<RptUserQueryParam> RptUserQueryParams { get; set; } = new List<RptUserQueryParam>();
}
