// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class RptUserQueryClause
{
    public int Id { get; set; }

    public int QueryId { get; set; }

    public string WhereType { get; set; } = null!;

    public virtual RptUserQuery Query { get; set; } = null!;

    public virtual ICollection<RptUserQueryParam> RptUserQueryParams { get; set; } = new List<RptUserQueryParam>();
}
