// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class SearchDBForStringResult
    {
        [StringLength(128)]
        public string SchemaName { get; set; } = default!;
        [StringLength(128)]
        public string TableName { get; set; } = default!;
        [StringLength(128)]
        public string ColumnName { get; set; } = default!;
    }
}

