// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class SearchinallResult
    {
        [StringLength(128)]
        public string? SP_Name { get; set; }
        [StringLength(2147483647)]
        public string? SP_Definition { get; set; }
    }
}

