// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace AF.ECT.Server.Models.ResultTypes;

public partial class SpecialCasesLodCase
{
    public string? Status { get; set; }

    public string? Position { get; set; }

    public string? Location { get; set; }
}
