// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace AF.ECT.Server.Models.ResultTypes
{
    public partial class SpecialCaseRFAGroupResult
    {
        [StringLength(100)]
        public string? Unit { get; set; }
        [StringLength(4)]
        public string? PAS { get; set; }
        [StringLength(100)]
        public string? CaseId { get; set; }
        public DateTime? DateSent { get; set; }
        [StringLength(150)]
        public string? ReasonSentBack { get; set; }
        [StringLength(2147483647)]
        public string? ExplanationForSendingBack { get; set; }
    }
}

